/**
 * ==========================================
 *     | GENERATED BY PG2ZOD |
 * ==========================================
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file was automatically generated from
 * your PostgreSQL database schema.
 *
 * To regenerate, run:
 *   pg2zod --url <connection-url> -o <file>
 *
 * Any manual changes will be overwritten when
 * the code is regenerated.
 * ==========================================
 */

import { z } from 'zod';

// ============================================
// Enums
// ============================================

/** PostgreSQL enum: asset_privacy */
export const PublicAssetPrivacySchema = z.enum(['inherit', 'private', 'public']);
export type PublicAssetPrivacy = z.infer<typeof PublicAssetPrivacySchema>;

/** PostgreSQL enum: permission_action */
export const PublicPermissionActionSchema = z.enum(['view', 'edit', 'comment', 'download', 'manage', 'share']);
export type PublicPermissionAction = z.infer<typeof PublicPermissionActionSchema>;

/** PostgreSQL enum: permission_scope */
export const PublicPermissionScopeSchema = z.enum(['organization', 'project', 'team', 'folder', 'collection', 'asset']);
export type PublicPermissionScope = z.infer<typeof PublicPermissionScopeSchema>;

/** PostgreSQL enum: share_scope */
export const PublicShareScopeSchema = z.enum(['asset', 'collection', 'project']);
export type PublicShareScope = z.infer<typeof PublicShareScopeSchema>;

// ============================================
// Domains
// ============================================

/** PostgreSQL domain: content_type (base: text) */
export const PublicContentTypeSchema = z.string().nullable() /* CHECK: CHECK ((VALUE ~ '^\S+\/\S+'::text)) */;
export type PublicContentType = z.infer<typeof PublicContentTypeSchema>;

/** PostgreSQL domain: http_method (base: text) */
export const PublicHttpMethodSchema = z.string().nullable();
export type PublicHttpMethod = z.infer<typeof PublicHttpMethodSchema>;

// ============================================
// Composite Types
// ============================================

/** PostgreSQL composite type: asset_acl */
export const PublicAssetAclCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** text */
  role: z.string().nullable(),
  /** boolean */
  can_view: z.boolean().nullable(),
  /** boolean */
  can_comment: z.boolean().nullable(),
  /** boolean */
  can_download: z.boolean().nullable(),
  /** boolean */
  can_edit: z.boolean().nullable(),
  /** boolean */
  can_share: z.boolean().nullable(),
  /** boolean */
  can_manage: z.boolean().nullable(),
  /** boolean */
  deny_view: z.boolean().nullable(),
  /** boolean */
  deny_comment: z.boolean().nullable(),
  /** boolean */
  deny_download: z.boolean().nullable(),
  /** boolean */
  deny_edit: z.boolean().nullable(),
  /** boolean */
  deny_share: z.boolean().nullable(),
  /** boolean */
  deny_manage: z.boolean().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicAssetAclComposite = z.infer<typeof PublicAssetAclCompositeSchema>;

/** PostgreSQL composite type: asset_collections */
export const PublicAssetCollectionsCompositeSchema = z.object({
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** uuid */
  collection_id: z.uuid().nullable(),
});
export type PublicAssetCollectionsComposite = z.infer<typeof PublicAssetCollectionsCompositeSchema>;

/** PostgreSQL composite type: asset_files */
export const PublicAssetFilesCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  asset_version_id: z.uuid().nullable(),
  /** text */
  role: z.string().nullable(),
  /** text */
  kind: z.string().nullable(),
  /** uuid */
  storage_id: z.uuid().nullable(),
  /** jsonb */
  metadata: z.record(z.string(), z.unknown()).nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
});
export type PublicAssetFilesComposite = z.infer<typeof PublicAssetFilesCompositeSchema>;

/** PostgreSQL composite type: asset_tags */
export const PublicAssetTagsCompositeSchema = z.object({
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** uuid */
  tag_id: z.uuid().nullable(),
});
export type PublicAssetTagsComposite = z.infer<typeof PublicAssetTagsCompositeSchema>;

/** PostgreSQL composite type: asset_versions */
export const PublicAssetVersionsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** integer */
  version_number: z.number().int().nullable(),
  /** text */
  label: z.string().nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicAssetVersionsComposite = z.infer<typeof PublicAssetVersionsCompositeSchema>;

/** PostgreSQL composite type: assets */
export const PublicAssetsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  organization_id: z.string().nullable(),
  /** text */
  project_id: z.string().nullable(),
  /** uuid */
  folder_id: z.uuid().nullable(),
  /** text */
  kind: z.string().nullable(),
  /** text */
  title: z.string().nullable(),
  /** text */
  description: z.string().nullable(),
  /** text */
  status: z.string().nullable(),
  /** integer */
  duration_ms: z.number().int().nullable(),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  fps_num: z.number().int().nullable(),
  /** integer */
  fps_den: z.number().int().nullable(),
  /** integer */
  audio_channels: z.number().int().nullable(),
  /** integer */
  page_count: z.number().int().nullable(),
  /** text[] */
  tags: z.unknown() /* unmapped type */.nullable(),
  /** tsvector */
  search_tsv: z.string() /* tsvector */.nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
  /** boolean */
  locked: z.boolean().nullable(),
  /** asset_privacy */
  privacy: PublicAssetPrivacySchema.nullable(),
});
export type PublicAssetsComposite = z.infer<typeof PublicAssetsCompositeSchema>;

/** PostgreSQL composite type: blog_posts */
export const PublicBlogPostsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  user_id: z.string().nullable(),
  /** text */
  title: z.string().nullable(),
  /** text */
  content: z.string().nullable(),
  /** text */
  excerpt: z.string().nullable(),
  /** text */
  slug: z.string().nullable(),
  /** text */
  status: z.string().nullable(),
  /** text */
  featured_image_url: z.string().nullable(),
  /** text[] */
  tags: z.unknown() /* unmapped type */.nullable(),
  /** text */
  meta_title: z.string().nullable(),
  /** text */
  meta_description: z.string().nullable(),
  /** timestamp with time zone */
  published_at: z.date().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicBlogPostsComposite = z.infer<typeof PublicBlogPostsCompositeSchema>;

/** PostgreSQL composite type: captions */
export const PublicCaptionsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** text */
  language: z.string().nullable(),
  /** text */
  label: z.string().nullable(),
  /** text */
  format: z.string().nullable(),
  /** uuid */
  storage_id: z.uuid().nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicCaptionsComposite = z.infer<typeof PublicCaptionsCompositeSchema>;

/** PostgreSQL composite type: collection_acl */
export const PublicCollectionAclCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  collection_id: z.uuid().nullable(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** boolean */
  can_view: z.boolean().nullable(),
  /** boolean */
  can_comment: z.boolean().nullable(),
  /** boolean */
  can_download: z.boolean().nullable(),
  /** boolean */
  can_edit: z.boolean().nullable(),
  /** boolean */
  can_share: z.boolean().nullable(),
  /** boolean */
  can_manage: z.boolean().nullable(),
  /** boolean */
  deny_view: z.boolean().nullable(),
  /** boolean */
  deny_comment: z.boolean().nullable(),
  /** boolean */
  deny_download: z.boolean().nullable(),
  /** boolean */
  deny_edit: z.boolean().nullable(),
  /** boolean */
  deny_share: z.boolean().nullable(),
  /** boolean */
  deny_manage: z.boolean().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicCollectionAclComposite = z.infer<typeof PublicCollectionAclCompositeSchema>;

/** PostgreSQL composite type: collections */
export const PublicCollectionsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  organization_id: z.string().nullable(),
  /** text */
  project_id: z.string().nullable(),
  /** uuid */
  parent_id: z.uuid().nullable(),
  /** text */
  name: z.string().nullable(),
  /** integer */
  position: z.number().int().nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
});
export type PublicCollectionsComposite = z.infer<typeof PublicCollectionsCompositeSchema>;

/** PostgreSQL composite type: comment_mentions */
export const PublicCommentMentionsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  comment_id: z.uuid().nullable(),
  /** text */
  mentioned_user_id: z.string().nullable(),
});
export type PublicCommentMentionsComposite = z.infer<typeof PublicCommentMentionsCompositeSchema>;

/** PostgreSQL composite type: comment_threads */
export const PublicCommentThreadsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  organization_id: z.string().nullable(),
  /** text */
  project_id: z.string().nullable(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** text */
  status: z.string().nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicCommentThreadsComposite = z.infer<typeof PublicCommentThreadsCompositeSchema>;

/** PostgreSQL composite type: comments */
export const PublicCommentsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  thread_id: z.uuid().nullable(),
  /** uuid */
  parent_comment_id: z.uuid().nullable(),
  /** text */
  author_id: z.string().nullable(),
  /** text */
  body: z.string().nullable(),
  /** integer */
  frame: z.number().int().nullable(),
  /** integer */
  timecode_ms: z.number().int().nullable(),
  /** numeric */
  pos_x: z.number().nullable(),
  /** numeric */
  pos_y: z.number().nullable(),
  /** jsonb */
  annotation: z.record(z.string(), z.unknown()).nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
});
export type PublicCommentsComposite = z.infer<typeof PublicCommentsCompositeSchema>;

/** PostgreSQL composite type: folder_acl */
export const PublicFolderAclCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  folder_id: z.uuid().nullable(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** boolean */
  can_view: z.boolean().nullable(),
  /** boolean */
  can_comment: z.boolean().nullable(),
  /** boolean */
  can_download: z.boolean().nullable(),
  /** boolean */
  can_edit: z.boolean().nullable(),
  /** boolean */
  can_share: z.boolean().nullable(),
  /** boolean */
  can_manage: z.boolean().nullable(),
  /** boolean */
  deny_view: z.boolean().nullable(),
  /** boolean */
  deny_comment: z.boolean().nullable(),
  /** boolean */
  deny_download: z.boolean().nullable(),
  /** boolean */
  deny_edit: z.boolean().nullable(),
  /** boolean */
  deny_share: z.boolean().nullable(),
  /** boolean */
  deny_manage: z.boolean().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicFolderAclComposite = z.infer<typeof PublicFolderAclCompositeSchema>;

/** PostgreSQL composite type: folders */
export const PublicFoldersCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  organization_id: z.string().nullable(),
  /** text */
  project_id: z.string().nullable(),
  /** uuid */
  parent_id: z.uuid().nullable(),
  /** text */
  name: z.string().nullable(),
  /** integer */
  position: z.number().int().nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
  /** boolean */
  locked: z.boolean().nullable(),
});
export type PublicFoldersComposite = z.infer<typeof PublicFoldersCompositeSchema>;

/** PostgreSQL composite type: http_header */
export const PublicHttpHeaderCompositeSchema = z.object({
  /** character varying */
  field: z.string().nullable(),
  /** character varying */
  value: z.string().nullable(),
});
export type PublicHttpHeaderComposite = z.infer<typeof PublicHttpHeaderCompositeSchema>;

/** PostgreSQL composite type: http_request */
export const PublicHttpRequestCompositeSchema = z.object({
  /** http_method */
  method: z.unknown() /* unmapped type */.nullable(),
  /** character varying */
  uri: z.string().nullable(),
  /** http_header[] */
  headers: z.unknown() /* unmapped type */.nullable(),
  /** character varying */
  content_type: z.string().nullable(),
  /** character varying */
  content: z.string().nullable(),
});
export type PublicHttpRequestComposite = z.infer<typeof PublicHttpRequestCompositeSchema>;

/** PostgreSQL composite type: http_response */
export const PublicHttpResponseCompositeSchema = z.object({
  /** integer */
  status: z.number().int().nullable(),
  /** character varying */
  content_type: z.string().nullable(),
  /** http_header[] */
  headers: z.unknown() /* unmapped type */.nullable(),
  /** character varying */
  content: z.string().nullable(),
});
export type PublicHttpResponseComposite = z.infer<typeof PublicHttpResponseCompositeSchema>;

/** PostgreSQL composite type: jobs */
export const PublicJobsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  organization_id: z.string().nullable(),
  /** text */
  project_id: z.string().nullable(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** uuid */
  source_version_id: z.uuid().nullable(),
  /** text */
  kind: z.string().nullable(),
  /** text */
  status: z.string().nullable(),
  /** text */
  provider: z.string().nullable(),
  /** jsonb */
  request_payload: z.record(z.string(), z.unknown()).nullable(),
  /** jsonb */
  result_payload: z.record(z.string(), z.unknown()).nullable(),
  /** timestamp with time zone */
  queued_at: z.date().nullable(),
  /** timestamp with time zone */
  started_at: z.date().nullable(),
  /** timestamp with time zone */
  finished_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicJobsComposite = z.infer<typeof PublicJobsCompositeSchema>;

/** PostgreSQL composite type: permission_audit */
export const PublicPermissionAuditCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  user_id: z.string().nullable(),
  /** text */
  scope_type: z.string().nullable(),
  /** text */
  scope_id: z.string().nullable(),
  /** text */
  action: z.string().nullable(),
  /** boolean */
  allowed: z.boolean().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
});
export type PublicPermissionAuditComposite = z.infer<typeof PublicPermissionAuditCompositeSchema>;

/** PostgreSQL composite type: person */
export const PublicPersonCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  first_name: z.string().nullable(),
  /** text */
  last_name: z.string().nullable(),
  /** text */
  gender: z.string().nullable(),
  /** date */
  date_of_birth: z.date().nullable(),
  /** text */
  email: z.string().nullable(),
  /** text */
  country_of_birth: z.string().nullable(),
});
export type PublicPersonComposite = z.infer<typeof PublicPersonCompositeSchema>;

/** PostgreSQL composite type: person_summary */
export const PublicPersonSummaryCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  first_name: z.string().nullable(),
  /** text */
  last_name: z.string().nullable(),
  /** text */
  email: z.string().nullable(),
});
export type PublicPersonSummaryComposite = z.infer<typeof PublicPersonSummaryCompositeSchema>;

/** PostgreSQL composite type: renditions */
export const PublicRenditionsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** uuid */
  source_version_id: z.uuid().nullable(),
  /** text */
  kind: z.string().nullable(),
  /** text */
  profile: z.string().nullable(),
  /** uuid */
  storage_id: z.uuid().nullable(),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  bitrate_kbps: z.number().int().nullable(),
  /** integer */
  duration_ms: z.number().int().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
});
export type PublicRenditionsComposite = z.infer<typeof PublicRenditionsCompositeSchema>;

/** PostgreSQL composite type: share_links */
export const PublicShareLinksCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  organization_id: z.string().nullable(),
  /** share_scope */
  scope_type: PublicShareScopeSchema.nullable(),
  /** uuid */
  scope_id: z.uuid().nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** text */
  code: z.string().nullable(),
  /** boolean */
  can_view: z.boolean().nullable(),
  /** boolean */
  can_comment: z.boolean().nullable(),
  /** boolean */
  can_download: z.boolean().nullable(),
  /** timestamp with time zone */
  expires_at: z.date().nullable(),
  /** text */
  password_hash: z.string().nullable(),
  /** timestamp with time zone */
  revoked_at: z.date().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
});
export type PublicShareLinksComposite = z.infer<typeof PublicShareLinksCompositeSchema>;

/** PostgreSQL composite type: storage_locations */
export const PublicStorageLocationsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  organization_id: z.string().nullable(),
  /** text */
  bucket: z.string().nullable(),
  /** text */
  key: z.string().nullable(),
  /** text */
  region: z.string().nullable(),
  /** text */
  etag: z.string().nullable(),
  /** bigint */
  size_bytes: z.bigint().nullable(),
  /** text */
  content_type: z.string().nullable(),
  /** text */
  checksum_sha256: z.string().nullable(),
  /** text */
  storage_class: z.string().nullable(),
  /** boolean */
  is_encrypted: z.boolean().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
});
export type PublicStorageLocationsComposite = z.infer<typeof PublicStorageLocationsCompositeSchema>;

/** PostgreSQL composite type: tags */
export const PublicTagsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  organization_id: z.string().nullable(),
  /** text */
  name: z.string().nullable(),
  /** text */
  color_hex: z.string().nullable(),
});
export type PublicTagsComposite = z.infer<typeof PublicTagsCompositeSchema>;

/** PostgreSQL composite type: thumbnails */
export const PublicThumbnailsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** text */
  role: z.string().nullable(),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  timecode_ms: z.number().int().nullable(),
  /** uuid */
  storage_id: z.uuid().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
});
export type PublicThumbnailsComposite = z.infer<typeof PublicThumbnailsCompositeSchema>;

/** PostgreSQL composite type: todos */
export const PublicTodosCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  user_id: z.string().nullable(),
  /** text */
  title: z.string().nullable(),
  /** text */
  description: z.string().nullable(),
  /** boolean */
  completed: z.boolean().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
  /** timestamp with time zone */
  completed_at: z.date().nullable(),
});
export type PublicTodosComposite = z.infer<typeof PublicTodosCompositeSchema>;

/** PostgreSQL composite type: upload_sessions */
export const PublicUploadSessionsCompositeSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** uuid */
  asset_version_id: z.uuid().nullable(),
  /** text */
  bucket: z.string().nullable(),
  /** text */
  object_key: z.string().nullable(),
  /** text */
  upload_id: z.string().nullable(),
  /** bigint */
  total_size_bytes: z.bigint().nullable(),
  /** text */
  content_type: z.string().nullable(),
  /** jsonb */
  parts: z.record(z.string(), z.unknown()).nullable(),
  /** text */
  status: z.string().nullable(),
  /** timestamp with time zone */
  last_heartbeat: z.date().nullable(),
  /** timestamp with time zone */
  created_at: z.date().nullable(),
});
export type PublicUploadSessionsComposite = z.infer<typeof PublicUploadSessionsCompositeSchema>;

// ============================================
// Tables
// ============================================

/** Table: public.asset_acl */
export const PublicAssetAclSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** text */
  role: z.enum(['view', 'edit']),
  /** boolean, default: true */
  can_view: z.boolean(),
  /** boolean, default: false */
  can_comment: z.boolean(),
  /** boolean, default: false */
  can_download: z.boolean(),
  /** boolean, default: false */
  can_edit: z.boolean(),
  /** boolean, default: false */
  can_share: z.boolean(),
  /** boolean, default: false */
  can_manage: z.boolean(),
  /** boolean, default: false */
  deny_view: z.boolean(),
  /** boolean, default: false */
  deny_comment: z.boolean(),
  /** boolean, default: false */
  deny_download: z.boolean(),
  /** boolean, default: false */
  deny_edit: z.boolean(),
  /** boolean, default: false */
  deny_share: z.boolean(),
  /** boolean, default: false */
  deny_manage: z.boolean(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicAssetAcl = z.infer<typeof PublicAssetAclSchema>;

/** Insert schema for asset_acl */
export const PublicAssetAclInsertSchema = PublicAssetAclSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** boolean, default: true */
  can_view: z.boolean().optional(),
  /** boolean, default: false */
  can_comment: z.boolean().optional(),
  /** boolean, default: false */
  can_download: z.boolean().optional(),
  /** boolean, default: false */
  can_edit: z.boolean().optional(),
  /** boolean, default: false */
  can_share: z.boolean().optional(),
  /** boolean, default: false */
  can_manage: z.boolean().optional(),
  /** boolean, default: false */
  deny_view: z.boolean().optional(),
  /** boolean, default: false */
  deny_comment: z.boolean().optional(),
  /** boolean, default: false */
  deny_download: z.boolean().optional(),
  /** boolean, default: false */
  deny_edit: z.boolean().optional(),
  /** boolean, default: false */
  deny_share: z.boolean().optional(),
  /** boolean, default: false */
  deny_manage: z.boolean().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicAssetAclInsert = z.infer<typeof PublicAssetAclInsertSchema>;

/** Update schema for asset_acl (all fields optional) */
export const PublicAssetAclUpdateSchema = PublicAssetAclSchema.partial();
export type PublicAssetAclUpdate = z.infer<typeof PublicAssetAclUpdateSchema>;

/** Table: public.asset_collections */
export const PublicAssetCollectionsSchema = z.object({
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  collection_id: z.uuid(),
});
export type PublicAssetCollections = z.infer<typeof PublicAssetCollectionsSchema>;

/** Insert schema for asset_collections */
export const PublicAssetCollectionsInsertSchema = PublicAssetCollectionsSchema;
export type PublicAssetCollectionsInsert = z.infer<typeof PublicAssetCollectionsInsertSchema>;

/** Update schema for asset_collections (all fields optional) */
export const PublicAssetCollectionsUpdateSchema = PublicAssetCollectionsSchema.partial();
export type PublicAssetCollectionsUpdate = z.infer<typeof PublicAssetCollectionsUpdateSchema>;

/** Table: public.asset_files */
export const PublicAssetFilesSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_version_id: z.uuid(),
  /** text */
  role: z.enum(['original', 'mezzanine', 'proxy', 'other']),
  /** text */
  kind: z.string(),
  /** uuid */
  storage_id: z.uuid(),
  /** jsonb, default: '{}'::jsonb */
  metadata: z.record(z.string(), z.unknown()),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicAssetFiles = z.infer<typeof PublicAssetFilesSchema>;

/** Insert schema for asset_files */
export const PublicAssetFilesInsertSchema = PublicAssetFilesSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** jsonb, default: '{}'::jsonb */
  metadata: z.record(z.string(), z.unknown()).optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicAssetFilesInsert = z.infer<typeof PublicAssetFilesInsertSchema>;

/** Update schema for asset_files (all fields optional) */
export const PublicAssetFilesUpdateSchema = PublicAssetFilesSchema.partial();
export type PublicAssetFilesUpdate = z.infer<typeof PublicAssetFilesUpdateSchema>;

/** Table: public.asset_tags */
export const PublicAssetTagsSchema = z.object({
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  tag_id: z.uuid(),
});
export type PublicAssetTags = z.infer<typeof PublicAssetTagsSchema>;

/** Insert schema for asset_tags */
export const PublicAssetTagsInsertSchema = PublicAssetTagsSchema;
export type PublicAssetTagsInsert = z.infer<typeof PublicAssetTagsInsertSchema>;

/** Update schema for asset_tags (all fields optional) */
export const PublicAssetTagsUpdateSchema = PublicAssetTagsSchema.partial();
export type PublicAssetTagsUpdate = z.infer<typeof PublicAssetTagsUpdateSchema>;

/** Table: public.asset_versions */
export const PublicAssetVersionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** integer */
  version_number: z.number().min(1).int(),
  /** text */
  label: z.string().nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
});
export type PublicAssetVersions = z.infer<typeof PublicAssetVersionsSchema>;

/** Insert schema for asset_versions */
export const PublicAssetVersionsInsertSchema = PublicAssetVersionsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
});
export type PublicAssetVersionsInsert = z.infer<typeof PublicAssetVersionsInsertSchema>;

/** Update schema for asset_versions (all fields optional) */
export const PublicAssetVersionsUpdateSchema = PublicAssetVersionsSchema.partial();
export type PublicAssetVersionsUpdate = z.infer<typeof PublicAssetVersionsUpdateSchema>;

/** Table: public.assets */
export const PublicAssetsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  folder_id: z.uuid().nullable(),
  /** text */
  kind: z.enum(['video', 'audio', 'image', 'document', 'other']),
  /** text */
  title: z.string(),
  /** text */
  description: z.string().nullable(),
  /** text, default: 'uploading'::text */
  status: z.enum(['uploading', 'ingesting', 'ready', 'error', 'archived']),
  /** integer */
  duration_ms: z.number().int().nullable(),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  fps_num: z.number().int().nullable(),
  /** integer */
  fps_den: z.number().int().nullable(),
  /** integer */
  audio_channels: z.number().int().nullable(),
  /** integer */
  page_count: z.number().int().nullable(),
  /** ARRAY */
  tags: z.array(z.string()).nullable(),
  /** tsvector */
  search_tsv: z.string() /* tsvector */.nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
  /** boolean, default: false */
  locked: z.boolean(),
  /** USER-DEFINED, default: 'inherit'::asset_privacy */
  privacy: PublicAssetPrivacySchema,
});
export type PublicAssets = z.infer<typeof PublicAssetsSchema>;

/** Insert schema for assets */
export const PublicAssetsInsertSchema = PublicAssetsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text, default: 'uploading'::text */
  status: z.enum(['uploading', 'ingesting', 'ready', 'error', 'archived']).optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
  /** boolean, default: false */
  locked: z.boolean().optional(),
  /** USER-DEFINED, default: 'inherit'::asset_privacy */
  privacy: PublicAssetPrivacySchema.optional(),
});
export type PublicAssetsInsert = z.infer<typeof PublicAssetsInsertSchema>;

/** Update schema for assets (all fields optional) */
export const PublicAssetsUpdateSchema = PublicAssetsSchema.partial();
export type PublicAssetsUpdate = z.infer<typeof PublicAssetsUpdateSchema>;

/** Table: public.blog_posts */
export const PublicBlogPostsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  user_id: z.string(),
  /** text */
  title: z.string(),
  /** text */
  content: z.string(),
  /** text */
  excerpt: z.string().nullable(),
  /** text */
  slug: z.string().nullable(),
  /** text, default: 'draft'::text */
  status: z.enum(['draft', 'published', 'archived']),
  /** text */
  featured_image_url: z.string().nullable(),
  /** ARRAY */
  tags: z.array(z.string()).nullable(),
  /** text */
  meta_title: z.string().nullable(),
  /** text */
  meta_description: z.string().nullable(),
  /** timestamp with time zone */
  published_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().nullable(),
});
export type PublicBlogPosts = z.infer<typeof PublicBlogPostsSchema>;

/** Insert schema for blog_posts */
export const PublicBlogPostsInsertSchema = PublicBlogPostsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text, default: 'draft'::text */
  status: z.enum(['draft', 'published', 'archived']).optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().nullable().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().nullable().optional(),
});
export type PublicBlogPostsInsert = z.infer<typeof PublicBlogPostsInsertSchema>;

/** Update schema for blog_posts (all fields optional) */
export const PublicBlogPostsUpdateSchema = PublicBlogPostsSchema.partial();
export type PublicBlogPostsUpdate = z.infer<typeof PublicBlogPostsUpdateSchema>;

/** Table: public.captions */
export const PublicCaptionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** text */
  language: z.string(),
  /** text */
  label: z.string().nullable(),
  /** text */
  format: z.enum(['vtt', 'srt']),
  /** uuid */
  storage_id: z.uuid(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
});
export type PublicCaptions = z.infer<typeof PublicCaptionsSchema>;

/** Insert schema for captions */
export const PublicCaptionsInsertSchema = PublicCaptionsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
});
export type PublicCaptionsInsert = z.infer<typeof PublicCaptionsInsertSchema>;

/** Update schema for captions (all fields optional) */
export const PublicCaptionsUpdateSchema = PublicCaptionsSchema.partial();
export type PublicCaptionsUpdate = z.infer<typeof PublicCaptionsUpdateSchema>;

/** Table: public.collection_acl */
export const PublicCollectionAclSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  collection_id: z.uuid(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** boolean, default: true */
  can_view: z.boolean(),
  /** boolean, default: false */
  can_comment: z.boolean(),
  /** boolean, default: false */
  can_download: z.boolean(),
  /** boolean, default: false */
  can_edit: z.boolean(),
  /** boolean, default: false */
  can_share: z.boolean(),
  /** boolean, default: false */
  can_manage: z.boolean(),
  /** boolean, default: false */
  deny_view: z.boolean(),
  /** boolean, default: false */
  deny_comment: z.boolean(),
  /** boolean, default: false */
  deny_download: z.boolean(),
  /** boolean, default: false */
  deny_edit: z.boolean(),
  /** boolean, default: false */
  deny_share: z.boolean(),
  /** boolean, default: false */
  deny_manage: z.boolean(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicCollectionAcl = z.infer<typeof PublicCollectionAclSchema>;

/** Insert schema for collection_acl */
export const PublicCollectionAclInsertSchema = PublicCollectionAclSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** boolean, default: true */
  can_view: z.boolean().optional(),
  /** boolean, default: false */
  can_comment: z.boolean().optional(),
  /** boolean, default: false */
  can_download: z.boolean().optional(),
  /** boolean, default: false */
  can_edit: z.boolean().optional(),
  /** boolean, default: false */
  can_share: z.boolean().optional(),
  /** boolean, default: false */
  can_manage: z.boolean().optional(),
  /** boolean, default: false */
  deny_view: z.boolean().optional(),
  /** boolean, default: false */
  deny_comment: z.boolean().optional(),
  /** boolean, default: false */
  deny_download: z.boolean().optional(),
  /** boolean, default: false */
  deny_edit: z.boolean().optional(),
  /** boolean, default: false */
  deny_share: z.boolean().optional(),
  /** boolean, default: false */
  deny_manage: z.boolean().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicCollectionAclInsert = z.infer<typeof PublicCollectionAclInsertSchema>;

/** Update schema for collection_acl (all fields optional) */
export const PublicCollectionAclUpdateSchema = PublicCollectionAclSchema.partial();
export type PublicCollectionAclUpdate = z.infer<typeof PublicCollectionAclUpdateSchema>;

/** Table: public.collections */
export const PublicCollectionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  parent_id: z.uuid().nullable(),
  /** text */
  name: z.string(),
  /** integer, default: 0 */
  position: z.number().int(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicCollections = z.infer<typeof PublicCollectionsSchema>;

/** Insert schema for collections */
export const PublicCollectionsInsertSchema = PublicCollectionsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** integer, default: 0 */
  position: z.number().int().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicCollectionsInsert = z.infer<typeof PublicCollectionsInsertSchema>;

/** Update schema for collections (all fields optional) */
export const PublicCollectionsUpdateSchema = PublicCollectionsSchema.partial();
export type PublicCollectionsUpdate = z.infer<typeof PublicCollectionsUpdateSchema>;

/** Table: public.comment_mentions */
export const PublicCommentMentionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  comment_id: z.uuid(),
  /** text */
  mentioned_user_id: z.string(),
});
export type PublicCommentMentions = z.infer<typeof PublicCommentMentionsSchema>;

/** Insert schema for comment_mentions */
export const PublicCommentMentionsInsertSchema = PublicCommentMentionsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
});
export type PublicCommentMentionsInsert = z.infer<typeof PublicCommentMentionsInsertSchema>;

/** Update schema for comment_mentions (all fields optional) */
export const PublicCommentMentionsUpdateSchema = PublicCommentMentionsSchema.partial();
export type PublicCommentMentionsUpdate = z.infer<typeof PublicCommentMentionsUpdateSchema>;

/** Table: public.comment_threads */
export const PublicCommentThreadsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  asset_id: z.uuid(),
  /** text, default: 'open'::text */
  status: z.enum(['open', 'resolved']),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
});
export type PublicCommentThreads = z.infer<typeof PublicCommentThreadsSchema>;

/** Insert schema for comment_threads */
export const PublicCommentThreadsInsertSchema = PublicCommentThreadsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text, default: 'open'::text */
  status: z.enum(['open', 'resolved']).optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
});
export type PublicCommentThreadsInsert = z.infer<typeof PublicCommentThreadsInsertSchema>;

/** Update schema for comment_threads (all fields optional) */
export const PublicCommentThreadsUpdateSchema = PublicCommentThreadsSchema.partial();
export type PublicCommentThreadsUpdate = z.infer<typeof PublicCommentThreadsUpdateSchema>;

/** Table: public.comments */
export const PublicCommentsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  thread_id: z.uuid(),
  /** uuid */
  parent_comment_id: z.uuid().nullable(),
  /** text */
  author_id: z.string().nullable(),
  /** text */
  body: z.string().nullable(),
  /** integer */
  frame: z.number().int().nullable(),
  /** integer */
  timecode_ms: z.number().int().nullable(),
  /** numeric */
  pos_x: z.number().nullable(),
  /** numeric */
  pos_y: z.number().nullable(),
  /** jsonb */
  annotation: z.record(z.string(), z.unknown()).nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicComments = z.infer<typeof PublicCommentsSchema>;

/** Insert schema for comments */
export const PublicCommentsInsertSchema = PublicCommentsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicCommentsInsert = z.infer<typeof PublicCommentsInsertSchema>;

/** Update schema for comments (all fields optional) */
export const PublicCommentsUpdateSchema = PublicCommentsSchema.partial();
export type PublicCommentsUpdate = z.infer<typeof PublicCommentsUpdateSchema>;

/** Table: public.folder_acl */
export const PublicFolderAclSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  folder_id: z.uuid(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** boolean, default: true */
  can_view: z.boolean(),
  /** boolean, default: false */
  can_comment: z.boolean(),
  /** boolean, default: false */
  can_download: z.boolean(),
  /** boolean, default: false */
  can_edit: z.boolean(),
  /** boolean, default: false */
  can_share: z.boolean(),
  /** boolean, default: false */
  can_manage: z.boolean(),
  /** boolean, default: false */
  deny_view: z.boolean(),
  /** boolean, default: false */
  deny_comment: z.boolean(),
  /** boolean, default: false */
  deny_download: z.boolean(),
  /** boolean, default: false */
  deny_edit: z.boolean(),
  /** boolean, default: false */
  deny_share: z.boolean(),
  /** boolean, default: false */
  deny_manage: z.boolean(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicFolderAcl = z.infer<typeof PublicFolderAclSchema>;

/** Insert schema for folder_acl */
export const PublicFolderAclInsertSchema = PublicFolderAclSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** boolean, default: true */
  can_view: z.boolean().optional(),
  /** boolean, default: false */
  can_comment: z.boolean().optional(),
  /** boolean, default: false */
  can_download: z.boolean().optional(),
  /** boolean, default: false */
  can_edit: z.boolean().optional(),
  /** boolean, default: false */
  can_share: z.boolean().optional(),
  /** boolean, default: false */
  can_manage: z.boolean().optional(),
  /** boolean, default: false */
  deny_view: z.boolean().optional(),
  /** boolean, default: false */
  deny_comment: z.boolean().optional(),
  /** boolean, default: false */
  deny_download: z.boolean().optional(),
  /** boolean, default: false */
  deny_edit: z.boolean().optional(),
  /** boolean, default: false */
  deny_share: z.boolean().optional(),
  /** boolean, default: false */
  deny_manage: z.boolean().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicFolderAclInsert = z.infer<typeof PublicFolderAclInsertSchema>;

/** Update schema for folder_acl (all fields optional) */
export const PublicFolderAclUpdateSchema = PublicFolderAclSchema.partial();
export type PublicFolderAclUpdate = z.infer<typeof PublicFolderAclUpdateSchema>;

/** Table: public.folders */
export const PublicFoldersSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  parent_id: z.uuid().nullable(),
  /** text */
  name: z.string(),
  /** integer, default: 0 */
  position: z.number().int(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
  /** boolean, default: false */
  locked: z.boolean(),
});
export type PublicFolders = z.infer<typeof PublicFoldersSchema>;

/** Insert schema for folders */
export const PublicFoldersInsertSchema = PublicFoldersSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** integer, default: 0 */
  position: z.number().int().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
  /** boolean, default: false */
  locked: z.boolean().optional(),
});
export type PublicFoldersInsert = z.infer<typeof PublicFoldersInsertSchema>;

/** Update schema for folders (all fields optional) */
export const PublicFoldersUpdateSchema = PublicFoldersSchema.partial();
export type PublicFoldersUpdate = z.infer<typeof PublicFoldersUpdateSchema>;

/** Table: public.jobs */
export const PublicJobsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** uuid */
  source_version_id: z.uuid().nullable(),
  /** text */
  kind: z.enum(['thumbnail', 'transcode']),
  /** text, default: 'queued'::text */
  status: z.enum(['queued', 'processing', 'succeeded', 'failed']),
  /** text */
  provider: z.string(),
  /** jsonb, default: '{}'::jsonb */
  request_payload: z.record(z.string(), z.unknown()),
  /** jsonb */
  result_payload: z.record(z.string(), z.unknown()).nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  queued_at: z.date(),
  /** timestamp with time zone */
  started_at: z.date().nullable(),
  /** timestamp with time zone */
  finished_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
});
export type PublicJobs = z.infer<typeof PublicJobsSchema>;

/** Insert schema for jobs */
export const PublicJobsInsertSchema = PublicJobsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text, default: 'queued'::text */
  status: z.enum(['queued', 'processing', 'succeeded', 'failed']).optional(),
  /** jsonb, default: '{}'::jsonb */
  request_payload: z.record(z.string(), z.unknown()).optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  queued_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
});
export type PublicJobsInsert = z.infer<typeof PublicJobsInsertSchema>;

/** Update schema for jobs (all fields optional) */
export const PublicJobsUpdateSchema = PublicJobsSchema.partial();
export type PublicJobsUpdate = z.infer<typeof PublicJobsUpdateSchema>;

/** Table: public.permission_audit */
export const PublicPermissionAuditSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  user_id: z.string(),
  /** text */
  scope_type: z.string(),
  /** text */
  scope_id: z.string(),
  /** text */
  action: z.string(),
  /** boolean */
  allowed: z.boolean(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicPermissionAudit = z.infer<typeof PublicPermissionAuditSchema>;

/** Insert schema for permission_audit */
export const PublicPermissionAuditInsertSchema = PublicPermissionAuditSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicPermissionAuditInsert = z.infer<typeof PublicPermissionAuditInsertSchema>;

/** Update schema for permission_audit (all fields optional) */
export const PublicPermissionAuditUpdateSchema = PublicPermissionAuditSchema.partial();
export type PublicPermissionAuditUpdate = z.infer<typeof PublicPermissionAuditUpdateSchema>;

/** Table: public.person */
export const PublicPersonSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  first_name: z.string(),
  /** text */
  last_name: z.string(),
  /** text */
  gender: z.string(),
  /** date */
  date_of_birth: z.date(),
  /** text */
  email: z.string().nullable(),
  /** text */
  country_of_birth: z.string(),
});
export type PublicPerson = z.infer<typeof PublicPersonSchema>;

/** Insert schema for person */
export const PublicPersonInsertSchema = PublicPersonSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
});
export type PublicPersonInsert = z.infer<typeof PublicPersonInsertSchema>;

/** Update schema for person (all fields optional) */
export const PublicPersonUpdateSchema = PublicPersonSchema.partial();
export type PublicPersonUpdate = z.infer<typeof PublicPersonUpdateSchema>;

/** Table: public.person_summary */
export const PublicPersonSummarySchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  first_name: z.string().nullable(),
  /** text */
  last_name: z.string().nullable(),
  /** text */
  email: z.string().nullable(),
});
export type PublicPersonSummary = z.infer<typeof PublicPersonSummarySchema>;

/** Insert schema for person_summary */
export const PublicPersonSummaryInsertSchema = PublicPersonSummarySchema;
export type PublicPersonSummaryInsert = z.infer<typeof PublicPersonSummaryInsertSchema>;

/** Update schema for person_summary (all fields optional) */
export const PublicPersonSummaryUpdateSchema = PublicPersonSummarySchema.partial();
export type PublicPersonSummaryUpdate = z.infer<typeof PublicPersonSummaryUpdateSchema>;

/** Table: public.renditions */
export const PublicRenditionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  source_version_id: z.uuid(),
  /** text */
  kind: z.enum(['progressive', 'hls', 'dash']),
  /** text */
  profile: z.string(),
  /** uuid */
  storage_id: z.uuid(),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  bitrate_kbps: z.number().int().nullable(),
  /** integer */
  duration_ms: z.number().int().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicRenditions = z.infer<typeof PublicRenditionsSchema>;

/** Insert schema for renditions */
export const PublicRenditionsInsertSchema = PublicRenditionsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicRenditionsInsert = z.infer<typeof PublicRenditionsInsertSchema>;

/** Update schema for renditions (all fields optional) */
export const PublicRenditionsUpdateSchema = PublicRenditionsSchema.partial();
export type PublicRenditionsUpdate = z.infer<typeof PublicRenditionsUpdateSchema>;

/** Table: public.share_links */
export const PublicShareLinksSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** USER-DEFINED */
  scope_type: PublicShareScopeSchema,
  /** uuid */
  scope_id: z.uuid(),
  /** text */
  created_by: z.string().nullable(),
  /** text */
  code: z.string(),
  /** boolean, default: true */
  can_view: z.boolean(),
  /** boolean, default: false */
  can_comment: z.boolean(),
  /** boolean, default: false */
  can_download: z.boolean(),
  /** timestamp with time zone */
  expires_at: z.date().nullable(),
  /** text */
  password_hash: z.string().nullable(),
  /** timestamp with time zone */
  revoked_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicShareLinks = z.infer<typeof PublicShareLinksSchema>;

/** Insert schema for share_links */
export const PublicShareLinksInsertSchema = PublicShareLinksSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** boolean, default: true */
  can_view: z.boolean().optional(),
  /** boolean, default: false */
  can_comment: z.boolean().optional(),
  /** boolean, default: false */
  can_download: z.boolean().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicShareLinksInsert = z.infer<typeof PublicShareLinksInsertSchema>;

/** Update schema for share_links (all fields optional) */
export const PublicShareLinksUpdateSchema = PublicShareLinksSchema.partial();
export type PublicShareLinksUpdate = z.infer<typeof PublicShareLinksUpdateSchema>;

/** Table: public.storage_locations */
export const PublicStorageLocationsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  bucket: z.string(),
  /** text */
  key: z.string(),
  /** text */
  region: z.string(),
  /** text */
  etag: z.string().nullable(),
  /** bigint */
  size_bytes: z.bigint().nullable(),
  /** text */
  content_type: z.string().nullable(),
  /** text */
  checksum_sha256: z.string().nullable(),
  /** text */
  storage_class: z.string().nullable(),
  /** boolean, default: true */
  is_encrypted: z.boolean().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicStorageLocations = z.infer<typeof PublicStorageLocationsSchema>;

/** Insert schema for storage_locations */
export const PublicStorageLocationsInsertSchema = PublicStorageLocationsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** boolean, default: true */
  is_encrypted: z.boolean().nullable().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicStorageLocationsInsert = z.infer<typeof PublicStorageLocationsInsertSchema>;

/** Update schema for storage_locations (all fields optional) */
export const PublicStorageLocationsUpdateSchema = PublicStorageLocationsSchema.partial();
export type PublicStorageLocationsUpdate = z.infer<typeof PublicStorageLocationsUpdateSchema>;

/** Table: public.tags */
export const PublicTagsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  name: z.string(),
  /** text */
  color_hex: z.string().nullable(),
});
export type PublicTags = z.infer<typeof PublicTagsSchema>;

/** Insert schema for tags */
export const PublicTagsInsertSchema = PublicTagsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
});
export type PublicTagsInsert = z.infer<typeof PublicTagsInsertSchema>;

/** Update schema for tags (all fields optional) */
export const PublicTagsUpdateSchema = PublicTagsSchema.partial();
export type PublicTagsUpdate = z.infer<typeof PublicTagsUpdateSchema>;

/** Table: public.thumbnails */
export const PublicThumbnailsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** text */
  role: z.enum(['poster', 'thumb', 'sprite']),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  timecode_ms: z.number().int().nullable(),
  /** uuid */
  storage_id: z.uuid(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicThumbnails = z.infer<typeof PublicThumbnailsSchema>;

/** Insert schema for thumbnails */
export const PublicThumbnailsInsertSchema = PublicThumbnailsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicThumbnailsInsert = z.infer<typeof PublicThumbnailsInsertSchema>;

/** Update schema for thumbnails (all fields optional) */
export const PublicThumbnailsUpdateSchema = PublicThumbnailsSchema.partial();
export type PublicThumbnailsUpdate = z.infer<typeof PublicThumbnailsUpdateSchema>;

/** Table: public.todos */
export const PublicTodosSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  user_id: z.string(),
  /** text */
  title: z.string(),
  /** text */
  description: z.string().nullable(),
  /** boolean, default: false */
  completed: z.boolean().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().nullable(),
  /** timestamp with time zone */
  completed_at: z.date().nullable(),
});
export type PublicTodos = z.infer<typeof PublicTodosSchema>;

/** Insert schema for todos */
export const PublicTodosInsertSchema = PublicTodosSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** boolean, default: false */
  completed: z.boolean().nullable().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().nullable().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().nullable().optional(),
});
export type PublicTodosInsert = z.infer<typeof PublicTodosInsertSchema>;

/** Update schema for todos (all fields optional) */
export const PublicTodosUpdateSchema = PublicTodosSchema.partial();
export type PublicTodosUpdate = z.infer<typeof PublicTodosUpdateSchema>;

/** Table: public.upload_sessions */
export const PublicUploadSessionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  asset_version_id: z.uuid(),
  /** text */
  bucket: z.string(),
  /** text */
  object_key: z.string(),
  /** text */
  upload_id: z.string(),
  /** bigint */
  total_size_bytes: z.bigint().nullable(),
  /** text */
  content_type: z.string().nullable(),
  /** jsonb, default: '[]'::jsonb */
  parts: z.record(z.string(), z.unknown()),
  /** text, default: 'in_progress'::text */
  status: z.enum(['in_progress', 'completed', 'aborted']),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  last_heartbeat: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicUploadSessions = z.infer<typeof PublicUploadSessionsSchema>;

/** Insert schema for upload_sessions */
export const PublicUploadSessionsInsertSchema = PublicUploadSessionsSchema.extend({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** jsonb, default: '[]'::jsonb */
  parts: z.record(z.string(), z.unknown()).optional(),
  /** text, default: 'in_progress'::text */
  status: z.enum(['in_progress', 'completed', 'aborted']).optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  last_heartbeat: z.date().nullable().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicUploadSessionsInsert = z.infer<typeof PublicUploadSessionsInsertSchema>;

/** Update schema for upload_sessions (all fields optional) */
export const PublicUploadSessionsUpdateSchema = PublicUploadSessionsSchema.partial();
export type PublicUploadSessionsUpdate = z.infer<typeof PublicUploadSessionsUpdateSchema>;

// ============================================
// Views
// ============================================

/** View: public.person_summary (read-only) */
export const PublicPersonSummaryViewSchema = z.object({
  /** uuid */
  id: z.uuid().nullable(),
  /** text */
  first_name: z.string().nullable(),
  /** text */
  last_name: z.string().nullable(),
  /** text */
  email: z.string().nullable(),
});
export type PublicPersonSummaryView = z.infer<typeof PublicPersonSummaryViewSchema>;

// ============================================
// Routines (Functions/Procedures)
// ============================================

/** FUNCTION: public.can_asset */
export const PublicCanAssetParamsSchema = z.object({
  /** uuid (IN) */
  p_asset_id: z.uuid(),
  /** USER-DEFINED (IN) */
  p_action: PublicPermissionActionSchema,
});
export type PublicCanAssetParams = z.infer<typeof PublicCanAssetParamsSchema>;

/** Returns: boolean */
export const PublicCanAssetReturnSchema = z.boolean();
export type PublicCanAssetReturn = z.infer<typeof PublicCanAssetReturnSchema>;

/** FUNCTION: public.can_collection */
export const PublicCanCollectionParamsSchema = z.object({
  /** uuid (IN) */
  p_collection_id: z.uuid(),
  /** USER-DEFINED (IN) */
  p_action: PublicPermissionActionSchema,
});
export type PublicCanCollectionParams = z.infer<typeof PublicCanCollectionParamsSchema>;

/** Returns: boolean */
export const PublicCanCollectionReturnSchema = z.boolean();
export type PublicCanCollectionReturn = z.infer<typeof PublicCanCollectionReturnSchema>;

/** FUNCTION: public.can_folder */
export const PublicCanFolderParamsSchema = z.object({
  /** uuid (IN) */
  p_folder_id: z.uuid(),
  /** USER-DEFINED (IN) */
  p_action: PublicPermissionActionSchema,
});
export type PublicCanFolderParams = z.infer<typeof PublicCanFolderParamsSchema>;

/** Returns: boolean */
export const PublicCanFolderReturnSchema = z.boolean();
export type PublicCanFolderReturn = z.infer<typeof PublicCanFolderReturnSchema>;

/** FUNCTION: public.can_organization */
export const PublicCanOrganizationParamsSchema = z.object({
  /** text (IN) */
  p_org_id: z.string(),
  /** USER-DEFINED (IN) */
  p_action: PublicPermissionActionSchema,
});
export type PublicCanOrganizationParams = z.infer<typeof PublicCanOrganizationParamsSchema>;

/** Returns: boolean */
export const PublicCanOrganizationReturnSchema = z.boolean();
export type PublicCanOrganizationReturn = z.infer<typeof PublicCanOrganizationReturnSchema>;

/** FUNCTION: public.can_project */
export const PublicCanProjectParamsSchema = z.object({
  /** text (IN) */
  p_project_id: z.string(),
  /** USER-DEFINED (IN) */
  p_action: PublicPermissionActionSchema,
});
export type PublicCanProjectParams = z.infer<typeof PublicCanProjectParamsSchema>;

/** Returns: boolean */
export const PublicCanProjectReturnSchema = z.boolean();
export type PublicCanProjectReturn = z.infer<typeof PublicCanProjectReturnSchema>;

/** FUNCTION: public.can_scope */
export const PublicCanScopeParamsSchema = z.object({
  /** text (IN) */
  p_scope: z.string(),
  /** text (IN) */
  p_id: z.string(),
  /** USER-DEFINED (IN) */
  p_action: PublicPermissionActionSchema,
});
export type PublicCanScopeParams = z.infer<typeof PublicCanScopeParamsSchema>;

/** Returns: boolean */
export const PublicCanScopeReturnSchema = z.boolean();
export type PublicCanScopeReturn = z.infer<typeof PublicCanScopeReturnSchema>;

/** FUNCTION: public.can_team */
export const PublicCanTeamParamsSchema = z.object({
  /** text (IN) */
  p_team_id: z.string(),
  /** USER-DEFINED (IN) */
  p_action: PublicPermissionActionSchema,
});
export type PublicCanTeamParams = z.infer<typeof PublicCanTeamParamsSchema>;

/** Returns: boolean */
export const PublicCanTeamReturnSchema = z.boolean();
export type PublicCanTeamReturn = z.infer<typeof PublicCanTeamReturnSchema>;

/** FUNCTION: public.log_permission_audit */
export const PublicLogPermissionAuditParamsSchema = z.object({
  /** text (IN) */
  p_user_id: z.string(),
  /** text (IN) */
  p_scope_type: z.string(),
  /** text (IN) */
  p_scope_id: z.string(),
  /** USER-DEFINED (IN) */
  p_action: PublicPermissionActionSchema,
  /** boolean (IN) */
  p_allowed: z.boolean(),
});
export type PublicLogPermissionAuditParams = z.infer<typeof PublicLogPermissionAuditParamsSchema>;


// ============================================
// Database Types
// ============================================

export interface Database {
  public: {
    Tables: {
      asset_acl: {
        Row: PublicAssetAcl;
        Insert: PublicAssetAclInsert;
        Update: PublicAssetAclUpdate;
        Relationships: [
          {
            foreignKeyName: "asset_acl_asset_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "assets"
            referencedColumns: []
          },
          {
            foreignKeyName: "asset_acl_group_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "groups"
            referencedColumns: []
          },
          {
            foreignKeyName: "asset_acl_user_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "user"
            referencedColumns: []
          },
        ];
      };
      asset_collections: {
        Row: PublicAssetCollections;
        Insert: PublicAssetCollectionsInsert;
        Update: PublicAssetCollectionsUpdate;
        Relationships: [
          {
            foreignKeyName: "asset_collections_asset_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: []
          },
          {
            foreignKeyName: "asset_collections_collection_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "collections"
            referencedColumns: []
          },
        ];
      };
      asset_files: {
        Row: PublicAssetFiles;
        Insert: PublicAssetFilesInsert;
        Update: PublicAssetFilesUpdate;
        Relationships: [
          {
            foreignKeyName: "asset_files_asset_version_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "asset_versions"
            referencedColumns: []
          },
          {
            foreignKeyName: "asset_files_storage_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "storage_locations"
            referencedColumns: []
          },
        ];
      };
      asset_tags: {
        Row: PublicAssetTags;
        Insert: PublicAssetTagsInsert;
        Update: PublicAssetTagsUpdate;
        Relationships: [
          {
            foreignKeyName: "asset_tags_asset_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: []
          },
          {
            foreignKeyName: "asset_tags_tag_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: []
          },
        ];
      };
      asset_versions: {
        Row: PublicAssetVersions;
        Insert: PublicAssetVersionsInsert;
        Update: PublicAssetVersionsUpdate;
        Relationships: [
          {
            foreignKeyName: "asset_versions_asset_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "assets"
            referencedColumns: []
          },
          {
            foreignKeyName: "asset_versions_created_by_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
        ];
      };
      assets: {
        Row: PublicAssets;
        Insert: PublicAssetsInsert;
        Update: PublicAssetsUpdate;
        Relationships: [
          {
            foreignKeyName: "assets_created_by_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
          {
            foreignKeyName: "assets_folder_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "folders"
            referencedColumns: []
          },
          {
            foreignKeyName: "assets_organization_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "organization"
            referencedColumns: []
          },
          {
            foreignKeyName: "assets_project_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "team"
            referencedColumns: []
          },
        ];
      };
      blog_posts: {
        Row: PublicBlogPosts;
        Insert: PublicBlogPostsInsert;
        Update: PublicBlogPostsUpdate;
        Relationships: [
          {
            foreignKeyName: "blog_posts_user_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
        ];
      };
      captions: {
        Row: PublicCaptions;
        Insert: PublicCaptionsInsert;
        Update: PublicCaptionsUpdate;
        Relationships: [
          {
            foreignKeyName: "captions_asset_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: []
          },
          {
            foreignKeyName: "captions_created_by_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
          {
            foreignKeyName: "captions_storage_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "storage_locations"
            referencedColumns: []
          },
        ];
      };
      collection_acl: {
        Row: PublicCollectionAcl;
        Insert: PublicCollectionAclInsert;
        Update: PublicCollectionAclUpdate;
        Relationships: [
          {
            foreignKeyName: "collection_acl_collection_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "collections"
            referencedColumns: []
          },
          {
            foreignKeyName: "collection_acl_group_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "groups"
            referencedColumns: []
          },
          {
            foreignKeyName: "collection_acl_user_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "user"
            referencedColumns: []
          },
        ];
      };
      collections: {
        Row: PublicCollections;
        Insert: PublicCollectionsInsert;
        Update: PublicCollectionsUpdate;
        Relationships: [
          {
            foreignKeyName: "collections_created_by_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
          {
            foreignKeyName: "collections_organization_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "organization"
            referencedColumns: []
          },
          {
            foreignKeyName: "collections_parent_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "collections"
            referencedColumns: []
          },
          {
            foreignKeyName: "collections_project_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "team"
            referencedColumns: []
          },
        ];
      };
      comment_mentions: {
        Row: PublicCommentMentions;
        Insert: PublicCommentMentionsInsert;
        Update: PublicCommentMentionsUpdate;
        Relationships: [
          {
            foreignKeyName: "comment_mentions_comment_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: []
          },
          {
            foreignKeyName: "comment_mentions_mentioned_user_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
        ];
      };
      comment_threads: {
        Row: PublicCommentThreads;
        Insert: PublicCommentThreadsInsert;
        Update: PublicCommentThreadsUpdate;
        Relationships: [
          {
            foreignKeyName: "comment_threads_asset_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: []
          },
          {
            foreignKeyName: "comment_threads_created_by_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
          {
            foreignKeyName: "comment_threads_organization_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "organization"
            referencedColumns: []
          },
          {
            foreignKeyName: "comment_threads_project_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "team"
            referencedColumns: []
          },
        ];
      };
      comments: {
        Row: PublicComments;
        Insert: PublicCommentsInsert;
        Update: PublicCommentsUpdate;
        Relationships: [
          {
            foreignKeyName: "comments_author_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
          {
            foreignKeyName: "comments_parent_comment_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: []
          },
          {
            foreignKeyName: "comments_thread_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "comment_threads"
            referencedColumns: []
          },
        ];
      };
      folder_acl: {
        Row: PublicFolderAcl;
        Insert: PublicFolderAclInsert;
        Update: PublicFolderAclUpdate;
        Relationships: [
          {
            foreignKeyName: "folder_acl_folder_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "folders"
            referencedColumns: []
          },
          {
            foreignKeyName: "folder_acl_group_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "groups"
            referencedColumns: []
          },
          {
            foreignKeyName: "folder_acl_user_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "user"
            referencedColumns: []
          },
        ];
      };
      folders: {
        Row: PublicFolders;
        Insert: PublicFoldersInsert;
        Update: PublicFoldersUpdate;
        Relationships: [
          {
            foreignKeyName: "folders_created_by_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
          {
            foreignKeyName: "folders_organization_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "organization"
            referencedColumns: []
          },
          {
            foreignKeyName: "folders_parent_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "folders"
            referencedColumns: []
          },
          {
            foreignKeyName: "folders_project_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "team"
            referencedColumns: []
          },
        ];
      };
      jobs: {
        Row: PublicJobs;
        Insert: PublicJobsInsert;
        Update: PublicJobsUpdate;
        Relationships: [
          {
            foreignKeyName: "jobs_asset_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: []
          },
          {
            foreignKeyName: "jobs_organization_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "organization"
            referencedColumns: []
          },
          {
            foreignKeyName: "jobs_project_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "team"
            referencedColumns: []
          },
          {
            foreignKeyName: "jobs_source_version_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "asset_versions"
            referencedColumns: []
          },
        ];
      };
      permission_audit: {
        Row: PublicPermissionAudit;
        Insert: PublicPermissionAuditInsert;
        Update: PublicPermissionAuditUpdate;
        Relationships: [
        ];
      };
      person: {
        Row: PublicPerson;
        Insert: PublicPersonInsert;
        Update: PublicPersonUpdate;
        Relationships: [
        ];
      };
      person_summary: {
        Row: PublicPersonSummary;
        Insert: PublicPersonSummaryInsert;
        Update: PublicPersonSummaryUpdate;
        Relationships: [
        ];
      };
      renditions: {
        Row: PublicRenditions;
        Insert: PublicRenditionsInsert;
        Update: PublicRenditionsUpdate;
        Relationships: [
          {
            foreignKeyName: "renditions_asset_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "assets"
            referencedColumns: []
          },
          {
            foreignKeyName: "renditions_source_version_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "asset_versions"
            referencedColumns: []
          },
          {
            foreignKeyName: "renditions_storage_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "storage_locations"
            referencedColumns: []
          },
        ];
      };
      share_links: {
        Row: PublicShareLinks;
        Insert: PublicShareLinksInsert;
        Update: PublicShareLinksUpdate;
        Relationships: [
          {
            foreignKeyName: "share_links_created_by_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
          {
            foreignKeyName: "share_links_organization_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "organization"
            referencedColumns: []
          },
        ];
      };
      storage_locations: {
        Row: PublicStorageLocations;
        Insert: PublicStorageLocationsInsert;
        Update: PublicStorageLocationsUpdate;
        Relationships: [
          {
            foreignKeyName: "storage_locations_organization_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "organization"
            referencedColumns: []
          },
        ];
      };
      tags: {
        Row: PublicTags;
        Insert: PublicTagsInsert;
        Update: PublicTagsUpdate;
        Relationships: [
          {
            foreignKeyName: "tags_organization_id_fkey"
            columns: []
            isOneToOne: true
            referencedRelation: "organization"
            referencedColumns: []
          },
        ];
      };
      thumbnails: {
        Row: PublicThumbnails;
        Insert: PublicThumbnailsInsert;
        Update: PublicThumbnailsUpdate;
        Relationships: [
          {
            foreignKeyName: "thumbnails_asset_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: []
          },
          {
            foreignKeyName: "thumbnails_storage_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "storage_locations"
            referencedColumns: []
          },
        ];
      };
      todos: {
        Row: PublicTodos;
        Insert: PublicTodosInsert;
        Update: PublicTodosUpdate;
        Relationships: [
          {
            foreignKeyName: "todos_user_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "user"
            referencedColumns: []
          },
        ];
      };
      upload_sessions: {
        Row: PublicUploadSessions;
        Insert: PublicUploadSessionsInsert;
        Update: PublicUploadSessionsUpdate;
        Relationships: [
          {
            foreignKeyName: "upload_sessions_asset_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "assets"
            referencedColumns: []
          },
          {
            foreignKeyName: "upload_sessions_asset_version_id_fkey"
            columns: []
            isOneToOne: false
            referencedRelation: "asset_versions"
            referencedColumns: []
          },
        ];
      };
    };
    Views: {
      [_ in never]: never
    };
    Functions: {
      canAsset: {
        Args: PublicCanAssetParams;
        Returns: PublicCanAssetReturn;
      };
      canCollection: {
        Args: PublicCanCollectionParams;
        Returns: PublicCanCollectionReturn;
      };
      canFolder: {
        Args: PublicCanFolderParams;
        Returns: PublicCanFolderReturn;
      };
      canOrganization: {
        Args: PublicCanOrganizationParams;
        Returns: PublicCanOrganizationReturn;
      };
      canProject: {
        Args: PublicCanProjectParams;
        Returns: PublicCanProjectReturn;
      };
      canScope: {
        Args: PublicCanScopeParams;
        Returns: PublicCanScopeReturn;
      };
      canTeam: {
        Args: PublicCanTeamParams;
        Returns: PublicCanTeamReturn;
      };
      logPermissionAudit: {
        Args: PublicLogPermissionAuditParams;
        Returns: void;
      };
    };
    Enums: {
      assetPrivacy: PublicAssetPrivacy;
      permissionAction: PublicPermissionAction;
      permissionScope: PublicPermissionScope;
      shareScope: PublicShareScope;
    };
    CompositeTypes: {
      assetAcl: PublicAssetAclComposite;
      assetCollections: PublicAssetCollectionsComposite;
      assetFiles: PublicAssetFilesComposite;
      assetTags: PublicAssetTagsComposite;
      assetVersions: PublicAssetVersionsComposite;
      assets: PublicAssetsComposite;
      blogPosts: PublicBlogPostsComposite;
      captions: PublicCaptionsComposite;
      collectionAcl: PublicCollectionAclComposite;
      collections: PublicCollectionsComposite;
      commentMentions: PublicCommentMentionsComposite;
      commentThreads: PublicCommentThreadsComposite;
      comments: PublicCommentsComposite;
      folderAcl: PublicFolderAclComposite;
      folders: PublicFoldersComposite;
      httpHeader: PublicHttpHeaderComposite;
      httpRequest: PublicHttpRequestComposite;
      httpResponse: PublicHttpResponseComposite;
      jobs: PublicJobsComposite;
      permissionAudit: PublicPermissionAuditComposite;
      person: PublicPersonComposite;
      personSummary: PublicPersonSummaryComposite;
      renditions: PublicRenditionsComposite;
      shareLinks: PublicShareLinksComposite;
      storageLocations: PublicStorageLocationsComposite;
      tags: PublicTagsComposite;
      thumbnails: PublicThumbnailsComposite;
      todos: PublicTodosComposite;
      uploadSessions: PublicUploadSessionsComposite;
    };
  };
}

// ============================================
// Warnings
// ============================================
// The following warnings were generated:
// - Unknown type: text[] (udt: text[]) in column tags
// - Unknown type: text[] (udt: text[]) in column tags
// - Unknown type: http_method (udt: http_method) in column method
// - Unknown type: http_header[] (udt: http_header[]) in column headers
// - Unknown type: http_header[] (udt: http_header[]) in column headers
