// Generated by pg-to-zod
// Do not edit manually

import { z } from 'zod';

// ============================================
// Enums
// ============================================

/** PostgreSQL enum: asset_privacy */
export const PublicAssetPrivacySchema = z.enum(['inherit', 'private', 'public']);
export type PublicAssetPrivacy = z.infer<typeof PublicAssetPrivacySchema>;

/** PostgreSQL enum: permission_action */
export const PublicPermissionActionSchema = z.enum(['view', 'edit', 'comment', 'download', 'manage', 'share']);
export type PublicPermissionAction = z.infer<typeof PublicPermissionActionSchema>;

/** PostgreSQL enum: permission_scope */
export const PublicPermissionScopeSchema = z.enum(['organization', 'project', 'team', 'folder', 'collection', 'asset']);
export type PublicPermissionScope = z.infer<typeof PublicPermissionScopeSchema>;

/** PostgreSQL enum: share_scope */
export const PublicShareScopeSchema = z.enum(['asset', 'collection', 'project']);
export type PublicShareScope = z.infer<typeof PublicShareScopeSchema>;

// ============================================
// Domains
// ============================================

/** PostgreSQL domain: content_type (base: text) */
export const PublicContentTypeSchema = z.string().nullable() /* CHECK: CHECK ((VALUE ~ '^\S+\/\S+'::text)) */;
export type PublicContentType = z.infer<typeof PublicContentTypeSchema>;

/** PostgreSQL domain: http_method (base: text) */
export const PublicHttpMethodSchema = z.string().nullable();
export type PublicHttpMethod = z.infer<typeof PublicHttpMethodSchema>;

// ============================================
// Tables
// ============================================

/** Table: public.asset_acl */
export const PublicAssetAclSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** text */
  role: z.enum(['view', 'edit']),
  /** boolean, default: true */
  can_view: z.boolean(),
  /** boolean, default: false */
  can_comment: z.boolean(),
  /** boolean, default: false */
  can_download: z.boolean(),
  /** boolean, default: false */
  can_edit: z.boolean(),
  /** boolean, default: false */
  can_share: z.boolean(),
  /** boolean, default: false */
  can_manage: z.boolean(),
  /** boolean, default: false */
  deny_view: z.boolean(),
  /** boolean, default: false */
  deny_comment: z.boolean(),
  /** boolean, default: false */
  deny_download: z.boolean(),
  /** boolean, default: false */
  deny_edit: z.boolean(),
  /** boolean, default: false */
  deny_share: z.boolean(),
  /** boolean, default: false */
  deny_manage: z.boolean(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicAssetAcl = z.infer<typeof PublicAssetAclSchema>;

/** Insert schema for asset_acl */
export const PublicAssetAclInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** text */
  role: z.enum(['view', 'edit']),
  /** boolean, default: true */
  can_view: z.boolean().optional(),
  /** boolean, default: false */
  can_comment: z.boolean().optional(),
  /** boolean, default: false */
  can_download: z.boolean().optional(),
  /** boolean, default: false */
  can_edit: z.boolean().optional(),
  /** boolean, default: false */
  can_share: z.boolean().optional(),
  /** boolean, default: false */
  can_manage: z.boolean().optional(),
  /** boolean, default: false */
  deny_view: z.boolean().optional(),
  /** boolean, default: false */
  deny_comment: z.boolean().optional(),
  /** boolean, default: false */
  deny_download: z.boolean().optional(),
  /** boolean, default: false */
  deny_edit: z.boolean().optional(),
  /** boolean, default: false */
  deny_share: z.boolean().optional(),
  /** boolean, default: false */
  deny_manage: z.boolean().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicAssetAclInsert = z.infer<typeof PublicAssetAclInsertSchema>;

/** Update schema for asset_acl (all fields optional) */
export const PublicAssetAclUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid().optional(),
  /** text */
  user_id: z.string().nullable().optional(),
  /** uuid */
  group_id: z.uuid().nullable().optional(),
  /** text */
  role: z.enum(['view', 'edit']).optional(),
  /** boolean */
  can_view: z.boolean().optional(),
  /** boolean */
  can_comment: z.boolean().optional(),
  /** boolean */
  can_download: z.boolean().optional(),
  /** boolean */
  can_edit: z.boolean().optional(),
  /** boolean */
  can_share: z.boolean().optional(),
  /** boolean */
  can_manage: z.boolean().optional(),
  /** boolean */
  deny_view: z.boolean().optional(),
  /** boolean */
  deny_comment: z.boolean().optional(),
  /** boolean */
  deny_download: z.boolean().optional(),
  /** boolean */
  deny_edit: z.boolean().optional(),
  /** boolean */
  deny_share: z.boolean().optional(),
  /** boolean */
  deny_manage: z.boolean().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().nullable().optional(),
});
export type PublicAssetAclUpdate = z.infer<typeof PublicAssetAclUpdateSchema>;

/** Table: public.asset_collections */
export const PublicAssetCollectionsSchema = z.object({
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  collection_id: z.uuid(),
});
export type PublicAssetCollections = z.infer<typeof PublicAssetCollectionsSchema>;

/** Insert schema for asset_collections */
export const PublicAssetCollectionsInsertSchema = z.object({
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  collection_id: z.uuid(),
});
export type PublicAssetCollectionsInsert = z.infer<typeof PublicAssetCollectionsInsertSchema>;

/** Update schema for asset_collections (all fields optional) */
export const PublicAssetCollectionsUpdateSchema = z.object({
  /** uuid */
  asset_id: z.uuid().optional(),
  /** uuid */
  collection_id: z.uuid().optional(),
});
export type PublicAssetCollectionsUpdate = z.infer<typeof PublicAssetCollectionsUpdateSchema>;

/** Table: public.asset_files */
export const PublicAssetFilesSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_version_id: z.uuid(),
  /** text */
  role: z.enum(['original', 'mezzanine', 'proxy', 'other']),
  /** text */
  kind: z.string(),
  /** uuid */
  storage_id: z.uuid(),
  /** jsonb, default: '{}'::jsonb */
  metadata: z.record(z.string(), z.unknown()),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicAssetFiles = z.infer<typeof PublicAssetFilesSchema>;

/** Insert schema for asset_files */
export const PublicAssetFilesInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  asset_version_id: z.uuid(),
  /** text */
  role: z.enum(['original', 'mezzanine', 'proxy', 'other']),
  /** text */
  kind: z.string(),
  /** uuid */
  storage_id: z.uuid(),
  /** jsonb, default: '{}'::jsonb */
  metadata: z.record(z.string(), z.unknown()).optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicAssetFilesInsert = z.infer<typeof PublicAssetFilesInsertSchema>;

/** Update schema for asset_files (all fields optional) */
export const PublicAssetFilesUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  asset_version_id: z.uuid().optional(),
  /** text */
  role: z.enum(['original', 'mezzanine', 'proxy', 'other']).optional(),
  /** text */
  kind: z.string().optional(),
  /** uuid */
  storage_id: z.uuid().optional(),
  /** jsonb */
  metadata: z.record(z.string(), z.unknown()).optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
});
export type PublicAssetFilesUpdate = z.infer<typeof PublicAssetFilesUpdateSchema>;

/** Table: public.asset_tags */
export const PublicAssetTagsSchema = z.object({
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  tag_id: z.uuid(),
});
export type PublicAssetTags = z.infer<typeof PublicAssetTagsSchema>;

/** Insert schema for asset_tags */
export const PublicAssetTagsInsertSchema = z.object({
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  tag_id: z.uuid(),
});
export type PublicAssetTagsInsert = z.infer<typeof PublicAssetTagsInsertSchema>;

/** Update schema for asset_tags (all fields optional) */
export const PublicAssetTagsUpdateSchema = z.object({
  /** uuid */
  asset_id: z.uuid().optional(),
  /** uuid */
  tag_id: z.uuid().optional(),
});
export type PublicAssetTagsUpdate = z.infer<typeof PublicAssetTagsUpdateSchema>;

/** Table: public.asset_versions */
export const PublicAssetVersionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** integer */
  version_number: z.number().min(1).int(),
  /** text */
  label: z.string().nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
});
export type PublicAssetVersions = z.infer<typeof PublicAssetVersionsSchema>;

/** Insert schema for asset_versions */
export const PublicAssetVersionsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid(),
  /** integer */
  version_number: z.number().min(1).int(),
  /** text */
  label: z.string().nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
});
export type PublicAssetVersionsInsert = z.infer<typeof PublicAssetVersionsInsertSchema>;

/** Update schema for asset_versions (all fields optional) */
export const PublicAssetVersionsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid().optional(),
  /** integer */
  version_number: z.number().min(1).int().optional(),
  /** text */
  label: z.string().nullable().optional(),
  /** text */
  created_by: z.string().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().optional(),
});
export type PublicAssetVersionsUpdate = z.infer<typeof PublicAssetVersionsUpdateSchema>;

/** Table: public.assets */
export const PublicAssetsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  folder_id: z.uuid().nullable(),
  /** text */
  kind: z.enum(['video', 'audio', 'image', 'document', 'other']),
  /** text */
  title: z.string(),
  /** text */
  description: z.string().nullable(),
  /** text, default: 'uploading'::text */
  status: z.enum(['uploading', 'ingesting', 'ready', 'error', 'archived']),
  /** integer */
  duration_ms: z.number().int().nullable(),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  fps_num: z.number().int().nullable(),
  /** integer */
  fps_den: z.number().int().nullable(),
  /** integer */
  audio_channels: z.number().int().nullable(),
  /** integer */
  page_count: z.number().int().nullable(),
  /** ARRAY */
  tags: z.array(z.unknown() /* unmapped type */).nullable(),
  /** tsvector */
  search_tsv: z.string() /* tsvector */.nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
  /** boolean, default: false */
  locked: z.boolean(),
  /** USER-DEFINED, default: 'inherit'::asset_privacy */
  privacy: PublicAssetPrivacySchema,
});
export type PublicAssets = z.infer<typeof PublicAssetsSchema>;

/** Insert schema for assets */
export const PublicAssetsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  folder_id: z.uuid().nullable(),
  /** text */
  kind: z.enum(['video', 'audio', 'image', 'document', 'other']),
  /** text */
  title: z.string(),
  /** text */
  description: z.string().nullable(),
  /** text, default: 'uploading'::text */
  status: z.enum(['uploading', 'ingesting', 'ready', 'error', 'archived']).optional(),
  /** integer */
  duration_ms: z.number().int().nullable(),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  fps_num: z.number().int().nullable(),
  /** integer */
  fps_den: z.number().int().nullable(),
  /** integer */
  audio_channels: z.number().int().nullable(),
  /** integer */
  page_count: z.number().int().nullable(),
  /** ARRAY */
  tags: z.array(z.unknown() /* unmapped type */).nullable(),
  /** tsvector */
  search_tsv: z.string() /* tsvector */.nullable(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
  /** boolean, default: false */
  locked: z.boolean().optional(),
  /** USER-DEFINED, default: 'inherit'::asset_privacy */
  privacy: PublicAssetPrivacySchema.optional(),
});
export type PublicAssetsInsert = z.infer<typeof PublicAssetsInsertSchema>;

/** Update schema for assets (all fields optional) */
export const PublicAssetsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string().optional(),
  /** text */
  project_id: z.string().optional(),
  /** uuid */
  folder_id: z.uuid().nullable().optional(),
  /** text */
  kind: z.enum(['video', 'audio', 'image', 'document', 'other']).optional(),
  /** text */
  title: z.string().optional(),
  /** text */
  description: z.string().nullable().optional(),
  /** text */
  status: z.enum(['uploading', 'ingesting', 'ready', 'error', 'archived']).optional(),
  /** integer */
  duration_ms: z.number().int().nullable().optional(),
  /** integer */
  width: z.number().int().nullable().optional(),
  /** integer */
  height: z.number().int().nullable().optional(),
  /** integer */
  fps_num: z.number().int().nullable().optional(),
  /** integer */
  fps_den: z.number().int().nullable().optional(),
  /** integer */
  audio_channels: z.number().int().nullable().optional(),
  /** integer */
  page_count: z.number().int().nullable().optional(),
  /** ARRAY */
  tags: z.array(z.unknown() /* unmapped type */).nullable().optional(),
  /** tsvector */
  search_tsv: z.string() /* tsvector */.nullable().optional(),
  /** text */
  created_by: z.string().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().optional(),
  /** boolean */
  locked: z.boolean().optional(),
  /** USER-DEFINED */
  privacy: PublicAssetPrivacySchema.optional(),
});
export type PublicAssetsUpdate = z.infer<typeof PublicAssetsUpdateSchema>;

/** Table: public.blog_posts */
export const PublicBlogPostsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  user_id: z.string(),
  /** text */
  title: z.string(),
  /** text */
  content: z.string(),
  /** text */
  excerpt: z.string().nullable(),
  /** text */
  slug: z.string().nullable(),
  /** text, default: 'draft'::text */
  status: z.enum(['draft', 'published', 'archived']),
  /** text */
  featured_image_url: z.string().nullable(),
  /** ARRAY */
  tags: z.array(z.unknown() /* unmapped type */).nullable(),
  /** text */
  meta_title: z.string().nullable(),
  /** text */
  meta_description: z.string().nullable(),
  /** timestamp with time zone */
  published_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().nullable(),
});
export type PublicBlogPosts = z.infer<typeof PublicBlogPostsSchema>;

/** Insert schema for blog_posts */
export const PublicBlogPostsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  user_id: z.string(),
  /** text */
  title: z.string(),
  /** text */
  content: z.string(),
  /** text */
  excerpt: z.string().nullable(),
  /** text */
  slug: z.string().nullable(),
  /** text, default: 'draft'::text */
  status: z.enum(['draft', 'published', 'archived']).optional(),
  /** text */
  featured_image_url: z.string().nullable(),
  /** ARRAY */
  tags: z.array(z.unknown() /* unmapped type */).nullable(),
  /** text */
  meta_title: z.string().nullable(),
  /** text */
  meta_description: z.string().nullable(),
  /** timestamp with time zone */
  published_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().nullable().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().nullable().optional(),
});
export type PublicBlogPostsInsert = z.infer<typeof PublicBlogPostsInsertSchema>;

/** Update schema for blog_posts (all fields optional) */
export const PublicBlogPostsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  user_id: z.string().optional(),
  /** text */
  title: z.string().optional(),
  /** text */
  content: z.string().optional(),
  /** text */
  excerpt: z.string().nullable().optional(),
  /** text */
  slug: z.string().nullable().optional(),
  /** text */
  status: z.enum(['draft', 'published', 'archived']).optional(),
  /** text */
  featured_image_url: z.string().nullable().optional(),
  /** ARRAY */
  tags: z.array(z.unknown() /* unmapped type */).nullable().optional(),
  /** text */
  meta_title: z.string().nullable().optional(),
  /** text */
  meta_description: z.string().nullable().optional(),
  /** timestamp with time zone */
  published_at: z.date().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().nullable().optional(),
  /** timestamp with time zone */
  updated_at: z.date().nullable().optional(),
});
export type PublicBlogPostsUpdate = z.infer<typeof PublicBlogPostsUpdateSchema>;

/** Table: public.captions */
export const PublicCaptionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** text */
  language: z.string(),
  /** text */
  label: z.string().nullable(),
  /** text */
  format: z.enum(['vtt', 'srt']),
  /** uuid */
  storage_id: z.uuid(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
});
export type PublicCaptions = z.infer<typeof PublicCaptionsSchema>;

/** Insert schema for captions */
export const PublicCaptionsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid(),
  /** text */
  language: z.string(),
  /** text */
  label: z.string().nullable(),
  /** text */
  format: z.enum(['vtt', 'srt']),
  /** uuid */
  storage_id: z.uuid(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
});
export type PublicCaptionsInsert = z.infer<typeof PublicCaptionsInsertSchema>;

/** Update schema for captions (all fields optional) */
export const PublicCaptionsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid().optional(),
  /** text */
  language: z.string().optional(),
  /** text */
  label: z.string().nullable().optional(),
  /** text */
  format: z.enum(['vtt', 'srt']).optional(),
  /** uuid */
  storage_id: z.uuid().optional(),
  /** text */
  created_by: z.string().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().optional(),
});
export type PublicCaptionsUpdate = z.infer<typeof PublicCaptionsUpdateSchema>;

/** Table: public.collection_acl */
export const PublicCollectionAclSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  collection_id: z.uuid(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** boolean, default: true */
  can_view: z.boolean(),
  /** boolean, default: false */
  can_comment: z.boolean(),
  /** boolean, default: false */
  can_download: z.boolean(),
  /** boolean, default: false */
  can_edit: z.boolean(),
  /** boolean, default: false */
  can_share: z.boolean(),
  /** boolean, default: false */
  can_manage: z.boolean(),
  /** boolean, default: false */
  deny_view: z.boolean(),
  /** boolean, default: false */
  deny_comment: z.boolean(),
  /** boolean, default: false */
  deny_download: z.boolean(),
  /** boolean, default: false */
  deny_edit: z.boolean(),
  /** boolean, default: false */
  deny_share: z.boolean(),
  /** boolean, default: false */
  deny_manage: z.boolean(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicCollectionAcl = z.infer<typeof PublicCollectionAclSchema>;

/** Insert schema for collection_acl */
export const PublicCollectionAclInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  collection_id: z.uuid(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** boolean, default: true */
  can_view: z.boolean().optional(),
  /** boolean, default: false */
  can_comment: z.boolean().optional(),
  /** boolean, default: false */
  can_download: z.boolean().optional(),
  /** boolean, default: false */
  can_edit: z.boolean().optional(),
  /** boolean, default: false */
  can_share: z.boolean().optional(),
  /** boolean, default: false */
  can_manage: z.boolean().optional(),
  /** boolean, default: false */
  deny_view: z.boolean().optional(),
  /** boolean, default: false */
  deny_comment: z.boolean().optional(),
  /** boolean, default: false */
  deny_download: z.boolean().optional(),
  /** boolean, default: false */
  deny_edit: z.boolean().optional(),
  /** boolean, default: false */
  deny_share: z.boolean().optional(),
  /** boolean, default: false */
  deny_manage: z.boolean().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicCollectionAclInsert = z.infer<typeof PublicCollectionAclInsertSchema>;

/** Update schema for collection_acl (all fields optional) */
export const PublicCollectionAclUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  collection_id: z.uuid().optional(),
  /** text */
  user_id: z.string().nullable().optional(),
  /** uuid */
  group_id: z.uuid().nullable().optional(),
  /** boolean */
  can_view: z.boolean().optional(),
  /** boolean */
  can_comment: z.boolean().optional(),
  /** boolean */
  can_download: z.boolean().optional(),
  /** boolean */
  can_edit: z.boolean().optional(),
  /** boolean */
  can_share: z.boolean().optional(),
  /** boolean */
  can_manage: z.boolean().optional(),
  /** boolean */
  deny_view: z.boolean().optional(),
  /** boolean */
  deny_comment: z.boolean().optional(),
  /** boolean */
  deny_download: z.boolean().optional(),
  /** boolean */
  deny_edit: z.boolean().optional(),
  /** boolean */
  deny_share: z.boolean().optional(),
  /** boolean */
  deny_manage: z.boolean().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().nullable().optional(),
});
export type PublicCollectionAclUpdate = z.infer<typeof PublicCollectionAclUpdateSchema>;

/** Table: public.collections */
export const PublicCollectionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  parent_id: z.uuid().nullable(),
  /** text */
  name: z.string(),
  /** integer, default: 0 */
  position: z.number().int(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicCollections = z.infer<typeof PublicCollectionsSchema>;

/** Insert schema for collections */
export const PublicCollectionsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  parent_id: z.uuid().nullable(),
  /** text */
  name: z.string(),
  /** integer, default: 0 */
  position: z.number().int().optional(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicCollectionsInsert = z.infer<typeof PublicCollectionsInsertSchema>;

/** Update schema for collections (all fields optional) */
export const PublicCollectionsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string().optional(),
  /** text */
  project_id: z.string().optional(),
  /** uuid */
  parent_id: z.uuid().nullable().optional(),
  /** text */
  name: z.string().optional(),
  /** integer */
  position: z.number().int().optional(),
  /** text */
  created_by: z.string().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
});
export type PublicCollectionsUpdate = z.infer<typeof PublicCollectionsUpdateSchema>;

/** Table: public.comment_mentions */
export const PublicCommentMentionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  comment_id: z.uuid(),
  /** text */
  mentioned_user_id: z.string(),
});
export type PublicCommentMentions = z.infer<typeof PublicCommentMentionsSchema>;

/** Insert schema for comment_mentions */
export const PublicCommentMentionsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  comment_id: z.uuid(),
  /** text */
  mentioned_user_id: z.string(),
});
export type PublicCommentMentionsInsert = z.infer<typeof PublicCommentMentionsInsertSchema>;

/** Update schema for comment_mentions (all fields optional) */
export const PublicCommentMentionsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  comment_id: z.uuid().optional(),
  /** text */
  mentioned_user_id: z.string().optional(),
});
export type PublicCommentMentionsUpdate = z.infer<typeof PublicCommentMentionsUpdateSchema>;

/** Table: public.comment_threads */
export const PublicCommentThreadsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  asset_id: z.uuid(),
  /** text, default: 'open'::text */
  status: z.enum(['open', 'resolved']),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
});
export type PublicCommentThreads = z.infer<typeof PublicCommentThreadsSchema>;

/** Insert schema for comment_threads */
export const PublicCommentThreadsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  asset_id: z.uuid(),
  /** text, default: 'open'::text */
  status: z.enum(['open', 'resolved']).optional(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
});
export type PublicCommentThreadsInsert = z.infer<typeof PublicCommentThreadsInsertSchema>;

/** Update schema for comment_threads (all fields optional) */
export const PublicCommentThreadsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string().optional(),
  /** text */
  project_id: z.string().optional(),
  /** uuid */
  asset_id: z.uuid().optional(),
  /** text */
  status: z.enum(['open', 'resolved']).optional(),
  /** text */
  created_by: z.string().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().optional(),
});
export type PublicCommentThreadsUpdate = z.infer<typeof PublicCommentThreadsUpdateSchema>;

/** Table: public.comments */
export const PublicCommentsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  thread_id: z.uuid(),
  /** uuid */
  parent_comment_id: z.uuid().nullable(),
  /** text */
  author_id: z.string().nullable(),
  /** text */
  body: z.string().nullable(),
  /** integer */
  frame: z.number().int().nullable(),
  /** integer */
  timecode_ms: z.number().int().nullable(),
  /** numeric */
  pos_x: z.number().nullable(),
  /** numeric */
  pos_y: z.number().nullable(),
  /** jsonb */
  annotation: z.record(z.string(), z.unknown()).nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicComments = z.infer<typeof PublicCommentsSchema>;

/** Insert schema for comments */
export const PublicCommentsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  thread_id: z.uuid(),
  /** uuid */
  parent_comment_id: z.uuid().nullable(),
  /** text */
  author_id: z.string().nullable(),
  /** text */
  body: z.string().nullable(),
  /** integer */
  frame: z.number().int().nullable(),
  /** integer */
  timecode_ms: z.number().int().nullable(),
  /** numeric */
  pos_x: z.number().nullable(),
  /** numeric */
  pos_y: z.number().nullable(),
  /** jsonb */
  annotation: z.record(z.string(), z.unknown()).nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicCommentsInsert = z.infer<typeof PublicCommentsInsertSchema>;

/** Update schema for comments (all fields optional) */
export const PublicCommentsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  thread_id: z.uuid().optional(),
  /** uuid */
  parent_comment_id: z.uuid().nullable().optional(),
  /** text */
  author_id: z.string().nullable().optional(),
  /** text */
  body: z.string().nullable().optional(),
  /** integer */
  frame: z.number().int().nullable().optional(),
  /** integer */
  timecode_ms: z.number().int().nullable().optional(),
  /** numeric */
  pos_x: z.number().nullable().optional(),
  /** numeric */
  pos_y: z.number().nullable().optional(),
  /** jsonb */
  annotation: z.record(z.string(), z.unknown()).nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
});
export type PublicCommentsUpdate = z.infer<typeof PublicCommentsUpdateSchema>;

/** Table: public.folder_acl */
export const PublicFolderAclSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  folder_id: z.uuid(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** boolean, default: true */
  can_view: z.boolean(),
  /** boolean, default: false */
  can_comment: z.boolean(),
  /** boolean, default: false */
  can_download: z.boolean(),
  /** boolean, default: false */
  can_edit: z.boolean(),
  /** boolean, default: false */
  can_share: z.boolean(),
  /** boolean, default: false */
  can_manage: z.boolean(),
  /** boolean, default: false */
  deny_view: z.boolean(),
  /** boolean, default: false */
  deny_comment: z.boolean(),
  /** boolean, default: false */
  deny_download: z.boolean(),
  /** boolean, default: false */
  deny_edit: z.boolean(),
  /** boolean, default: false */
  deny_share: z.boolean(),
  /** boolean, default: false */
  deny_manage: z.boolean(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicFolderAcl = z.infer<typeof PublicFolderAclSchema>;

/** Insert schema for folder_acl */
export const PublicFolderAclInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  folder_id: z.uuid(),
  /** text */
  user_id: z.string().nullable(),
  /** uuid */
  group_id: z.uuid().nullable(),
  /** boolean, default: true */
  can_view: z.boolean().optional(),
  /** boolean, default: false */
  can_comment: z.boolean().optional(),
  /** boolean, default: false */
  can_download: z.boolean().optional(),
  /** boolean, default: false */
  can_edit: z.boolean().optional(),
  /** boolean, default: false */
  can_share: z.boolean().optional(),
  /** boolean, default: false */
  can_manage: z.boolean().optional(),
  /** boolean, default: false */
  deny_view: z.boolean().optional(),
  /** boolean, default: false */
  deny_comment: z.boolean().optional(),
  /** boolean, default: false */
  deny_download: z.boolean().optional(),
  /** boolean, default: false */
  deny_edit: z.boolean().optional(),
  /** boolean, default: false */
  deny_share: z.boolean().optional(),
  /** boolean, default: false */
  deny_manage: z.boolean().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().nullable(),
});
export type PublicFolderAclInsert = z.infer<typeof PublicFolderAclInsertSchema>;

/** Update schema for folder_acl (all fields optional) */
export const PublicFolderAclUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  folder_id: z.uuid().optional(),
  /** text */
  user_id: z.string().nullable().optional(),
  /** uuid */
  group_id: z.uuid().nullable().optional(),
  /** boolean */
  can_view: z.boolean().optional(),
  /** boolean */
  can_comment: z.boolean().optional(),
  /** boolean */
  can_download: z.boolean().optional(),
  /** boolean */
  can_edit: z.boolean().optional(),
  /** boolean */
  can_share: z.boolean().optional(),
  /** boolean */
  can_manage: z.boolean().optional(),
  /** boolean */
  deny_view: z.boolean().optional(),
  /** boolean */
  deny_comment: z.boolean().optional(),
  /** boolean */
  deny_download: z.boolean().optional(),
  /** boolean */
  deny_edit: z.boolean().optional(),
  /** boolean */
  deny_share: z.boolean().optional(),
  /** boolean */
  deny_manage: z.boolean().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().nullable().optional(),
});
export type PublicFolderAclUpdate = z.infer<typeof PublicFolderAclUpdateSchema>;

/** Table: public.folders */
export const PublicFoldersSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  parent_id: z.uuid().nullable(),
  /** text */
  name: z.string(),
  /** integer, default: 0 */
  position: z.number().int(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
  /** boolean, default: false */
  locked: z.boolean(),
});
export type PublicFolders = z.infer<typeof PublicFoldersSchema>;

/** Insert schema for folders */
export const PublicFoldersInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  parent_id: z.uuid().nullable(),
  /** text */
  name: z.string(),
  /** integer, default: 0 */
  position: z.number().int().optional(),
  /** text */
  created_by: z.string().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
  /** boolean, default: false */
  locked: z.boolean().optional(),
});
export type PublicFoldersInsert = z.infer<typeof PublicFoldersInsertSchema>;

/** Update schema for folders (all fields optional) */
export const PublicFoldersUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string().optional(),
  /** text */
  project_id: z.string().optional(),
  /** uuid */
  parent_id: z.uuid().nullable().optional(),
  /** text */
  name: z.string().optional(),
  /** integer */
  position: z.number().int().optional(),
  /** text */
  created_by: z.string().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
  /** timestamp with time zone */
  updated_at: z.date().optional(),
  /** boolean */
  locked: z.boolean().optional(),
});
export type PublicFoldersUpdate = z.infer<typeof PublicFoldersUpdateSchema>;

/** Table: public.jobs */
export const PublicJobsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** uuid */
  source_version_id: z.uuid().nullable(),
  /** text */
  kind: z.enum(['thumbnail', 'transcode']),
  /** text, default: 'queued'::text */
  status: z.enum(['queued', 'processing', 'succeeded', 'failed']),
  /** text */
  provider: z.string(),
  /** jsonb, default: '{}'::jsonb */
  request_payload: z.record(z.string(), z.unknown()),
  /** jsonb */
  result_payload: z.record(z.string(), z.unknown()).nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  queued_at: z.date(),
  /** timestamp with time zone */
  started_at: z.date().nullable(),
  /** timestamp with time zone */
  finished_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date(),
});
export type PublicJobs = z.infer<typeof PublicJobsSchema>;

/** Insert schema for jobs */
export const PublicJobsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string(),
  /** text */
  project_id: z.string(),
  /** uuid */
  asset_id: z.uuid().nullable(),
  /** uuid */
  source_version_id: z.uuid().nullable(),
  /** text */
  kind: z.enum(['thumbnail', 'transcode']),
  /** text, default: 'queued'::text */
  status: z.enum(['queued', 'processing', 'succeeded', 'failed']).optional(),
  /** text */
  provider: z.string(),
  /** jsonb, default: '{}'::jsonb */
  request_payload: z.record(z.string(), z.unknown()).optional(),
  /** jsonb */
  result_payload: z.record(z.string(), z.unknown()).nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  queued_at: z.date().optional(),
  /** timestamp with time zone */
  started_at: z.date().nullable(),
  /** timestamp with time zone */
  finished_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().optional(),
});
export type PublicJobsInsert = z.infer<typeof PublicJobsInsertSchema>;

/** Update schema for jobs (all fields optional) */
export const PublicJobsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string().optional(),
  /** text */
  project_id: z.string().optional(),
  /** uuid */
  asset_id: z.uuid().nullable().optional(),
  /** uuid */
  source_version_id: z.uuid().nullable().optional(),
  /** text */
  kind: z.enum(['thumbnail', 'transcode']).optional(),
  /** text */
  status: z.enum(['queued', 'processing', 'succeeded', 'failed']).optional(),
  /** text */
  provider: z.string().optional(),
  /** jsonb */
  request_payload: z.record(z.string(), z.unknown()).optional(),
  /** jsonb */
  result_payload: z.record(z.string(), z.unknown()).nullable().optional(),
  /** timestamp with time zone */
  queued_at: z.date().optional(),
  /** timestamp with time zone */
  started_at: z.date().nullable().optional(),
  /** timestamp with time zone */
  finished_at: z.date().nullable().optional(),
  /** timestamp with time zone */
  updated_at: z.date().optional(),
});
export type PublicJobsUpdate = z.infer<typeof PublicJobsUpdateSchema>;

/** Table: public.permission_audit */
export const PublicPermissionAuditSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  user_id: z.string(),
  /** text */
  scope_type: z.string(),
  /** text */
  scope_id: z.string(),
  /** text */
  action: z.string(),
  /** boolean */
  allowed: z.boolean(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicPermissionAudit = z.infer<typeof PublicPermissionAuditSchema>;

/** Insert schema for permission_audit */
export const PublicPermissionAuditInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  user_id: z.string(),
  /** text */
  scope_type: z.string(),
  /** text */
  scope_id: z.string(),
  /** text */
  action: z.string(),
  /** boolean */
  allowed: z.boolean(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicPermissionAuditInsert = z.infer<typeof PublicPermissionAuditInsertSchema>;

/** Update schema for permission_audit (all fields optional) */
export const PublicPermissionAuditUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  user_id: z.string().optional(),
  /** text */
  scope_type: z.string().optional(),
  /** text */
  scope_id: z.string().optional(),
  /** text */
  action: z.string().optional(),
  /** boolean */
  allowed: z.boolean().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
});
export type PublicPermissionAuditUpdate = z.infer<typeof PublicPermissionAuditUpdateSchema>;

/** Table: public.person */
export const PublicPersonSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  first_name: z.string(),
  /** text */
  last_name: z.string(),
  /** text */
  gender: z.string(),
  /** date */
  date_of_birth: z.date(),
  /** text */
  email: z.string().nullable(),
  /** text */
  country_of_birth: z.string(),
});
export type PublicPerson = z.infer<typeof PublicPersonSchema>;

/** Insert schema for person */
export const PublicPersonInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  first_name: z.string(),
  /** text */
  last_name: z.string(),
  /** text */
  gender: z.string(),
  /** date */
  date_of_birth: z.date(),
  /** text */
  email: z.string().nullable(),
  /** text */
  country_of_birth: z.string(),
});
export type PublicPersonInsert = z.infer<typeof PublicPersonInsertSchema>;

/** Update schema for person (all fields optional) */
export const PublicPersonUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  first_name: z.string().optional(),
  /** text */
  last_name: z.string().optional(),
  /** text */
  gender: z.string().optional(),
  /** date */
  date_of_birth: z.date().optional(),
  /** text */
  email: z.string().nullable().optional(),
  /** text */
  country_of_birth: z.string().optional(),
});
export type PublicPersonUpdate = z.infer<typeof PublicPersonUpdateSchema>;

/** Table: public.renditions */
export const PublicRenditionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  source_version_id: z.uuid(),
  /** text */
  kind: z.enum(['progressive', 'hls', 'dash']),
  /** text */
  profile: z.string(),
  /** uuid */
  storage_id: z.uuid(),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  bitrate_kbps: z.number().int().nullable(),
  /** integer */
  duration_ms: z.number().int().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicRenditions = z.infer<typeof PublicRenditionsSchema>;

/** Insert schema for renditions */
export const PublicRenditionsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  source_version_id: z.uuid(),
  /** text */
  kind: z.enum(['progressive', 'hls', 'dash']),
  /** text */
  profile: z.string(),
  /** uuid */
  storage_id: z.uuid(),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  bitrate_kbps: z.number().int().nullable(),
  /** integer */
  duration_ms: z.number().int().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicRenditionsInsert = z.infer<typeof PublicRenditionsInsertSchema>;

/** Update schema for renditions (all fields optional) */
export const PublicRenditionsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid().optional(),
  /** uuid */
  source_version_id: z.uuid().optional(),
  /** text */
  kind: z.enum(['progressive', 'hls', 'dash']).optional(),
  /** text */
  profile: z.string().optional(),
  /** uuid */
  storage_id: z.uuid().optional(),
  /** integer */
  width: z.number().int().nullable().optional(),
  /** integer */
  height: z.number().int().nullable().optional(),
  /** integer */
  bitrate_kbps: z.number().int().nullable().optional(),
  /** integer */
  duration_ms: z.number().int().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
});
export type PublicRenditionsUpdate = z.infer<typeof PublicRenditionsUpdateSchema>;

/** Table: public.share_links */
export const PublicShareLinksSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** USER-DEFINED */
  scope_type: PublicShareScopeSchema,
  /** uuid */
  scope_id: z.uuid(),
  /** text */
  created_by: z.string().nullable(),
  /** text */
  code: z.string(),
  /** boolean, default: true */
  can_view: z.boolean(),
  /** boolean, default: false */
  can_comment: z.boolean(),
  /** boolean, default: false */
  can_download: z.boolean(),
  /** timestamp with time zone */
  expires_at: z.date().nullable(),
  /** text */
  password_hash: z.string().nullable(),
  /** timestamp with time zone */
  revoked_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicShareLinks = z.infer<typeof PublicShareLinksSchema>;

/** Insert schema for share_links */
export const PublicShareLinksInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string(),
  /** USER-DEFINED */
  scope_type: PublicShareScopeSchema,
  /** uuid */
  scope_id: z.uuid(),
  /** text */
  created_by: z.string().nullable(),
  /** text */
  code: z.string(),
  /** boolean, default: true */
  can_view: z.boolean().optional(),
  /** boolean, default: false */
  can_comment: z.boolean().optional(),
  /** boolean, default: false */
  can_download: z.boolean().optional(),
  /** timestamp with time zone */
  expires_at: z.date().nullable(),
  /** text */
  password_hash: z.string().nullable(),
  /** timestamp with time zone */
  revoked_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicShareLinksInsert = z.infer<typeof PublicShareLinksInsertSchema>;

/** Update schema for share_links (all fields optional) */
export const PublicShareLinksUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string().optional(),
  /** USER-DEFINED */
  scope_type: PublicShareScopeSchema.optional(),
  /** uuid */
  scope_id: z.uuid().optional(),
  /** text */
  created_by: z.string().nullable().optional(),
  /** text */
  code: z.string().optional(),
  /** boolean */
  can_view: z.boolean().optional(),
  /** boolean */
  can_comment: z.boolean().optional(),
  /** boolean */
  can_download: z.boolean().optional(),
  /** timestamp with time zone */
  expires_at: z.date().nullable().optional(),
  /** text */
  password_hash: z.string().nullable().optional(),
  /** timestamp with time zone */
  revoked_at: z.date().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
});
export type PublicShareLinksUpdate = z.infer<typeof PublicShareLinksUpdateSchema>;

/** Table: public.storage_locations */
export const PublicStorageLocationsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  bucket: z.string(),
  /** text */
  key: z.string(),
  /** text */
  region: z.string(),
  /** text */
  etag: z.string().nullable(),
  /** bigint */
  size_bytes: z.bigint().nullable(),
  /** text */
  content_type: z.string().nullable(),
  /** text */
  checksum_sha256: z.string().nullable(),
  /** text */
  storage_class: z.string().nullable(),
  /** boolean, default: true */
  is_encrypted: z.boolean().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicStorageLocations = z.infer<typeof PublicStorageLocationsSchema>;

/** Insert schema for storage_locations */
export const PublicStorageLocationsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string(),
  /** text */
  bucket: z.string(),
  /** text */
  key: z.string(),
  /** text */
  region: z.string(),
  /** text */
  etag: z.string().nullable(),
  /** bigint */
  size_bytes: z.bigint().nullable(),
  /** text */
  content_type: z.string().nullable(),
  /** text */
  checksum_sha256: z.string().nullable(),
  /** text */
  storage_class: z.string().nullable(),
  /** boolean, default: true */
  is_encrypted: z.boolean().nullable().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicStorageLocationsInsert = z.infer<typeof PublicStorageLocationsInsertSchema>;

/** Update schema for storage_locations (all fields optional) */
export const PublicStorageLocationsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string().optional(),
  /** text */
  bucket: z.string().optional(),
  /** text */
  key: z.string().optional(),
  /** text */
  region: z.string().optional(),
  /** text */
  etag: z.string().nullable().optional(),
  /** bigint */
  size_bytes: z.bigint().nullable().optional(),
  /** text */
  content_type: z.string().nullable().optional(),
  /** text */
  checksum_sha256: z.string().nullable().optional(),
  /** text */
  storage_class: z.string().nullable().optional(),
  /** boolean */
  is_encrypted: z.boolean().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
});
export type PublicStorageLocationsUpdate = z.infer<typeof PublicStorageLocationsUpdateSchema>;

/** Table: public.tags */
export const PublicTagsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  organization_id: z.string(),
  /** text */
  name: z.string(),
  /** text */
  color_hex: z.string().nullable(),
});
export type PublicTags = z.infer<typeof PublicTagsSchema>;

/** Insert schema for tags */
export const PublicTagsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string(),
  /** text */
  name: z.string(),
  /** text */
  color_hex: z.string().nullable(),
});
export type PublicTagsInsert = z.infer<typeof PublicTagsInsertSchema>;

/** Update schema for tags (all fields optional) */
export const PublicTagsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  organization_id: z.string().optional(),
  /** text */
  name: z.string().optional(),
  /** text */
  color_hex: z.string().nullable().optional(),
});
export type PublicTagsUpdate = z.infer<typeof PublicTagsUpdateSchema>;

/** Table: public.thumbnails */
export const PublicThumbnailsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** text */
  role: z.enum(['poster', 'thumb', 'sprite']),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  timecode_ms: z.number().int().nullable(),
  /** uuid */
  storage_id: z.uuid(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicThumbnails = z.infer<typeof PublicThumbnailsSchema>;

/** Insert schema for thumbnails */
export const PublicThumbnailsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid(),
  /** text */
  role: z.enum(['poster', 'thumb', 'sprite']),
  /** integer */
  width: z.number().int().nullable(),
  /** integer */
  height: z.number().int().nullable(),
  /** integer */
  timecode_ms: z.number().int().nullable(),
  /** uuid */
  storage_id: z.uuid(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicThumbnailsInsert = z.infer<typeof PublicThumbnailsInsertSchema>;

/** Update schema for thumbnails (all fields optional) */
export const PublicThumbnailsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid().optional(),
  /** text */
  role: z.enum(['poster', 'thumb', 'sprite']).optional(),
  /** integer */
  width: z.number().int().nullable().optional(),
  /** integer */
  height: z.number().int().nullable().optional(),
  /** integer */
  timecode_ms: z.number().int().nullable().optional(),
  /** uuid */
  storage_id: z.uuid().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
});
export type PublicThumbnailsUpdate = z.infer<typeof PublicThumbnailsUpdateSchema>;

/** Table: public.todos */
export const PublicTodosSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** text */
  user_id: z.string(),
  /** text */
  title: z.string(),
  /** text */
  description: z.string().nullable(),
  /** boolean, default: false */
  completed: z.boolean().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().nullable(),
  /** timestamp with time zone */
  completed_at: z.date().nullable(),
});
export type PublicTodos = z.infer<typeof PublicTodosSchema>;

/** Insert schema for todos */
export const PublicTodosInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** text */
  user_id: z.string(),
  /** text */
  title: z.string(),
  /** text */
  description: z.string().nullable(),
  /** boolean, default: false */
  completed: z.boolean().nullable().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().nullable().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  updated_at: z.date().nullable().optional(),
  /** timestamp with time zone */
  completed_at: z.date().nullable(),
});
export type PublicTodosInsert = z.infer<typeof PublicTodosInsertSchema>;

/** Update schema for todos (all fields optional) */
export const PublicTodosUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** text */
  user_id: z.string().optional(),
  /** text */
  title: z.string().optional(),
  /** text */
  description: z.string().nullable().optional(),
  /** boolean */
  completed: z.boolean().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().nullable().optional(),
  /** timestamp with time zone */
  updated_at: z.date().nullable().optional(),
  /** timestamp with time zone */
  completed_at: z.date().nullable().optional(),
});
export type PublicTodosUpdate = z.infer<typeof PublicTodosUpdateSchema>;

/** Table: public.upload_sessions */
export const PublicUploadSessionsSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid(),
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  asset_version_id: z.uuid(),
  /** text */
  bucket: z.string(),
  /** text */
  object_key: z.string(),
  /** text */
  upload_id: z.string(),
  /** bigint */
  total_size_bytes: z.bigint().nullable(),
  /** text */
  content_type: z.string().nullable(),
  /** jsonb, default: '[]'::jsonb */
  parts: z.record(z.string(), z.unknown()),
  /** text, default: 'in_progress'::text */
  status: z.enum(['in_progress', 'completed', 'aborted']),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  last_heartbeat: z.date().nullable(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date(),
});
export type PublicUploadSessions = z.infer<typeof PublicUploadSessionsSchema>;

/** Insert schema for upload_sessions */
export const PublicUploadSessionsInsertSchema = z.object({
  /** uuid, default: gen_random_uuid() */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid(),
  /** uuid */
  asset_version_id: z.uuid(),
  /** text */
  bucket: z.string(),
  /** text */
  object_key: z.string(),
  /** text */
  upload_id: z.string(),
  /** bigint */
  total_size_bytes: z.bigint().nullable(),
  /** text */
  content_type: z.string().nullable(),
  /** jsonb, default: '[]'::jsonb */
  parts: z.record(z.string(), z.unknown()).optional(),
  /** text, default: 'in_progress'::text */
  status: z.enum(['in_progress', 'completed', 'aborted']).optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  last_heartbeat: z.date().nullable().optional(),
  /** timestamp with time zone, default: CURRENT_TIMESTAMP */
  created_at: z.date().optional(),
});
export type PublicUploadSessionsInsert = z.infer<typeof PublicUploadSessionsInsertSchema>;

/** Update schema for upload_sessions (all fields optional) */
export const PublicUploadSessionsUpdateSchema = z.object({
  /** uuid */
  id: z.uuid().optional(),
  /** uuid */
  asset_id: z.uuid().optional(),
  /** uuid */
  asset_version_id: z.uuid().optional(),
  /** text */
  bucket: z.string().optional(),
  /** text */
  object_key: z.string().optional(),
  /** text */
  upload_id: z.string().optional(),
  /** bigint */
  total_size_bytes: z.bigint().nullable().optional(),
  /** text */
  content_type: z.string().nullable().optional(),
  /** jsonb */
  parts: z.record(z.string(), z.unknown()).optional(),
  /** text */
  status: z.enum(['in_progress', 'completed', 'aborted']).optional(),
  /** timestamp with time zone */
  last_heartbeat: z.date().nullable().optional(),
  /** timestamp with time zone */
  created_at: z.date().optional(),
});
export type PublicUploadSessionsUpdate = z.infer<typeof PublicUploadSessionsUpdateSchema>;

// ============================================
// Warnings
// ============================================
// The following warnings were generated:
// - Unknown type: array (udt: _text) in column tags
// - Unknown type: array (udt: _text) in column tags
// - Unknown type: array (udt: _text) in column tags
// - Unknown type: array (udt: _text) in column tags
// - Unknown type: array (udt: _text) in column tags
// - Unknown type: array (udt: _text) in column tags
